"""Generate radius-five Bresenham paths; the endpoint itself does not block sight."""

from pathlib import Path


def paths():
    data = []
    for dy in range(-5, 6):
        for dx in range(-5, 6):
            if abs(dx) + abs(dy) > 5:
                continue
            data.append((dy + 5) * 16 + dx + 5)
            x = y = 0
            ax, ay = abs(dx), abs(dy)
            error = ax - ay
            while (x, y) != (dx, dy):
                data.append((y + 5) * 16 + x + 5)
                twice = 2 * error
                if twice > -ay:
                    error -= ay
                    x += 1 if dx >= 0 else -1
                if twice < ax:
                    error += ax
                    y += 1 if dy >= 0 else -1
            data.append(255)
    return data + [255]


if __name__ == "__main__":
    data = paths()
    lines = [
        "; Generated by make_sight_rays.py. Target, blocking cells, 255.",
        "SIGHT_RAYS:",
    ]
    lines += [
        "    .byte " + ",".join(map(str, data[i : i + 16]))
        for i in range(0, len(data), 16)
    ]
    Path(__file__).with_name("src").joinpath("sight_rays.inc").write_text(
        "\n".join(lines) + "\n"
    )
