[entry]
pc = "$0300"
sp = "$00FF"

[vectors]
nmi = "$FFFC"
reset = "$FFFE"
irq = "$FFFA"

[mem]
ram_start = "$0300"
ram_end = "$7FFF"
rom_start = "$8000"
rom_end = "$FFFF"
vram_base = "$C100"

[io]
kbd_matrix = "$C800"
sound_port = "$C804"

[cpu]
model = "MB8861H"
clock_hz = 894000
