; T2 counts continuously from $FFFF. Sample high/low/high to avoid a torn read.
; Do not reload on each tick: rendering time remains part of the ten seconds.
CLOCK_RELOAD:
    LDAA #$FF
    STAA $C808
    STAA $C809
    JSR CLOCK_READ
    LDX CLOCK_NOW
    STX CLOCK_PREV
    CLR CLOCK_ACC
    CLR CLOCK_ACC + 1
    CLR CLOCK_OVER
    CLR CLOCK_MAX
    CLR CLOCK_MAX + 1
    RTS
CLOCK_READ:
    LDAA $C809
    STAA CLOCK_NOW
    LDAA $C808
    STAA CLOCK_NOW + 1
    LDAA $C809
    CMPA CLOCK_NOW
    BNE CLOCK_READ
    RTS
CLOCK_SERVICE:
    PSHA
    PSHB
    STX CLOCK_X
    JSR CLOCK_READ
    LDAA CLOCK_PREV + 1
    SUBA CLOCK_NOW + 1
    STAA CLOCK_DELTA + 1
    LDAA CLOCK_PREV
    SBCA CLOCK_NOW
    STAA CLOCK_DELTA
    LDX CLOCK_NOW
    STX CLOCK_PREV
    LDAA CLOCK_DELTA
    CMPA CLOCK_MAX
    BHI CLOCK_MAX_STORE
    BCS CLOCK_MAX_DONE
    LDAA CLOCK_DELTA + 1
    CMPA CLOCK_MAX + 1
    BLS CLOCK_MAX_DONE
CLOCK_MAX_STORE:
    LDX CLOCK_DELTA
    STX CLOCK_MAX
CLOCK_MAX_DONE:
    CLR CLOCK_OVER
    LDAA CLOCK_ACC + 1
    ADDA CLOCK_DELTA + 1
    STAA CLOCK_ACC + 1
    LDAA CLOCK_ACC
    ADCA CLOCK_DELTA
    STAA CLOCK_ACC
    BCC CLOCK_CATCH_UP
    INC CLOCK_OVER
CLOCK_CATCH_UP:
    TST CLOCK_OVER
    BNE CLOCK_TICK
    LDAA CLOCK_ACC
    CMPA #$3A
    BCS CLOCK_DONE
    BHI CLOCK_TICK
    LDAA CLOCK_ACC + 1
    CMPA #$34
    BCS CLOCK_DONE
CLOCK_TICK:
    LDAA CLOCK_ACC + 1
    SUBA #$34
    STAA CLOCK_ACC + 1
    LDAA CLOCK_ACC
    SBCA #$3A
    STAA CLOCK_ACC
    BCC CLOCK_NO_BORROW
    CLR CLOCK_OVER
CLOCK_NO_BORROW:
    INC TICK
    JSR SOUND_TICK
    JSR TIMER_TICK
    JSR INPUT_CAPTURE
    BRA CLOCK_CATCH_UP
CLOCK_DONE:
    LDX CLOCK_X
    PULB
    PULA
    RTS
TIMER_TICK:
    LDAA MODE
    CMPA #1
    BNE TIMER_DONE
    LDX TIME_LEFT
    BEQ TIMER_DONE
    DEX
    STX TIME_LEFT
    BNE TIMER_DONE
TIMER_EXPIRED:
    INC TIMED_OUT
TIMER_DONE:
    RTS
