TEXT_TABLE:
    STX TABLE_PTR
TEXT_TABLE_NEXT:
    LDX TABLE_PTR
    LDAA 0,X
    ORAA 1,X
    BEQ TEXT_TABLE_DONE
    LDX 0,X
    STX TEXT_OUT
    LDX TABLE_PTR
    LDX 2,X
    STX TEXT_PTR
    JSR TEXT
    LDX TABLE_PTR
    ADX #4
    STX TABLE_PTR
    BRA TEXT_TABLE_NEXT
TEXT_TABLE_DONE:
    RTS
POINTER_INDEX:
    ASLA
    TAB
POINTER_LOOP:
    TSTB
    BEQ POINTER_READ
    INX
    DECB
    BRA POINTER_LOOP
POINTER_READ:
    LDX 0,X
    RTS
DRAW_TITLE:
    LDX #TITLE_SCREEN
    STX SRC
    LDX #FRAMEBUFFER
    STX DST
    LDX #768
    STX COUNT
    JSR COPY
    LDX #TITLE_TEXT
    JSR TEXT_TABLE
    JMP PRESENT
DRAW_HELP:
    JSR CLEAR_SCREEN
    LDX #HELP_TEXT
    JSR TEXT_TABLE
    JMP PRESENT
DRAW_GAME:
    JSR CLEAR_SCREEN
    LDX #HUD_TEXT
    JSR TEXT_TABLE
    LDAA SECONDS
    STAA OLD_SECONDS
    CLR SECONDS
    LDX TIME_LEFT
    STX TIME_WORK
SECONDS_DIVIDE:
    TST TIME_WORK
    BNE SECONDS_SUBTRACT
    LDAA TIME_WORK + 1
    CMPA #60
    BCS SECONDS_REMAINDER
SECONDS_SUBTRACT:
    LDAA TIME_WORK + 1
    SUBA #60
    STAA TIME_WORK + 1
    LDAA TIME_WORK
    SBCA #0
    STAA TIME_WORK
    INC SECONDS
    BRA SECONDS_DIVIDE
SECONDS_REMAINDER:
    LDX TIME_WORK
    CPX #0
    BEQ SECONDS_READY
    INC SECONDS
SECONDS_READY:
    LDAA SECONDS
    CMPA OLD_SECONDS
    BEQ DRAW_SECONDS
    CMPA #4
    BCC DRAW_SECONDS
    LDX #SFX_TICK
    JSR PLAY_SFX
DRAW_SECONDS:
    LDAA SECONDS
    LDX #FRAMEBUFFER + 5
    JSR NUMBER
    LDAA LOOPS
    LDX #FRAMEBUFFER + 15
    JSR NUMBER
    LDAA ROOM
    INCA
    LDX #FRAMEBUFFER + 27
    JSR NUMBER
    LDAA SECONDS
    ASLA
    TAB
    LDX #FRAMEBUFFER + 32
    LDAA #$9E
DRAW_TIME_BAR:
    TSTB
    BEQ DRAW_SEALS
    STAA 0,X
    INX
    DECB
    BRA DRAW_TIME_BAR
DRAW_SEALS:
    CLR INDEX
    LDX #FRAMEBUFFER + 32 + 20
    STX DRAW_PTR
DRAW_SEAL:
    LDAA INDEX
    JSR FLAG_TEST
    TSTA
    BEQ SEAL_UNLIT
    LDAA #$9E
    BRA SEAL_SHOW
SEAL_UNLIT:
    LDAA #13
SEAL_SHOW:
    LDX DRAW_PTR
    STAA 0,X
    INX
    STX DRAW_PTR
    INC INDEX
    LDAA INDEX
    CMPA #12
    BCS DRAW_SEAL
    JSR ROOM_OPEN
    STAA OPENED
    LDAA ROOM
    LDX #ROOM_NAMES
    JSR POINTER_INDEX
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 32 * 22 + 1
    STX TEXT_OUT
    JSR TEXT
    CLR DRAW_Y
    LDX #MAP
    STX MAP_PTR
    LDX #FRAMEBUFFER + 64
    STX DRAW_PTR
DRAW_ROW:
    CLR DRAW_X
DRAW_CELL:
    LDX MAP_PTR
    LDAA 0,X
    INX
    STX MAP_PTR
    TSTA
    BEQ FLOOR_TILE
    CMPA #1
    BEQ WALL_TILE
    CMPA #2
    BEQ SEAL_TILE
    CMPA #4
    BEQ GATE_TILE
    CMPA #5
    BEQ HAZARD_TILE
    LDAA #$94
    BRA ACTOR_TILE
FLOOR_TILE:
    LDAA #$40
    BRA ACTOR_TILE
WALL_TILE:
    LDAA #$80
    BRA ACTOR_TILE
SEAL_TILE:
    LDAA #$8C
    TST OPENED
    BEQ ACTOR_TILE
    LDAA #$90
    BRA ACTOR_TILE
GATE_TILE:
    LDAA #$88
    TST OPENED
    BEQ ACTOR_TILE
    LDAA #$40
    BRA ACTOR_TILE
HAZARD_TILE:
    LDAA #$98
ACTOR_TILE:
    STAA DRAW_TILE
    LDAA DRAW_X
    CMPA PLAYER_X
    BNE DRAW_TILE_READY
    LDAA DRAW_Y
    CMPA PLAYER_Y
    BNE DRAW_TILE_READY
    LDAA #$84
    STAA DRAW_TILE
DRAW_TILE_READY:
    LDX DRAW_PTR
    LDAA DRAW_TILE
    STAA 0,X
    CMPA #$40
    BEQ DRAW_FLOOR_REST
    INCA
    STAA 1,X
    INCA
    STAA 32,X
    INCA
    STAA 33,X
    BRA DRAW_NEXT
DRAW_FLOOR_REST:
    STAA 1,X
    STAA 32,X
    STAA 33,X
DRAW_NEXT:
    INX
    INX
    STX DRAW_PTR
    INC DRAW_X
    LDAA DRAW_X
    CMPA #16
    BCS DRAW_CELL
    LDX DRAW_PTR
    ADX #32
    STX DRAW_PTR
    JSR CLOCK_SERVICE
    INC DRAW_Y
    LDAA DRAW_Y
    CMPA #10
    BCS DRAW_ROW
    JMP PRESENT
DRAW_WIN:
    JSR CLEAR_SCREEN
    LDX #WIN_TEXT
    JSR TEXT_TABLE
    LDAA LOOPS
    LDX #FRAMEBUFFER + 32 * 16 + 14
    JSR NUMBER
    JMP PRESENT
