GAME_START:
SHOW_TITLE:
    CLR MODE
    LDX #TITLE_PCG
    JSR LOAD_PCG
    LDX #MUSIC_TITLE
    JSR PLAY_MUSIC
    JSR DRAW_TITLE
    JMP FRAME_READY
IDLE:
    JSR CLOCK_SERVICE
    TST TIMED_OUT
    BNE REWIND
    LDAA MODE
    CMPA #1
    BNE INPUT_IDLE
    LDAA TICK
    SUBA DRAW_LAST
    CMPA #6
    BCS INPUT_IDLE
    LDAA TICK
    STAA DRAW_LAST
    JSR DRAW_GAME
INPUT_IDLE:
    JSR INPUT_CAPTURE
    LDAA KEY_PENDING
    BEQ HELD_INPUT
    CLR KEY_PENDING
DISPATCH:
    STAA ACTION
    TST TIMED_OUT
    BNE REWIND
    LDAA TICK
    STAA MOVE_LAST
    LDAA MODE
    BEQ TITLE_INPUT
    CMPA #1
    BEQ GAME_INPUT
    JMP SHOW_TITLE
HELD_INPUT:
    LDAA MODE
    CMPA #1
    BNE IDLE
    LDAA TICK
    SUBA MOVE_LAST
    CMPA #6
    BCS IDLE
    LDAA KEY_LAST
    BEQ IDLE
    CMPA #4
    BHI IDLE
    JMP DISPATCH
TITLE_INPUT:
    LDAA ACTION
    CMPA #5
    BEQ NEW_GAME
    LDAA #4
    STAA MODE
    JSR DRAW_HELP
    JMP FRAME_READY
NEW_GAME:
    CLR FLAGS
    CLR FLAGS + 1
    CLR LOOPS
    JSR SOUND_STOP
    LDX #GAME_PCG
    JSR LOAD_PCG
REWIND:
    CLR TIMED_OUT
    LDAA #2
    STAA MODE
    CLR ROOM
    LDAA LOOPS
    CMPA #255
    BEQ REWIND_COUNTED
    INC LOOPS
REWIND_COUNTED:
    LDAA #2
    STAA PLAYER_X
    LDAA #4
    STAA PLAYER_Y
    LDX #600
    STX TIME_LEFT
    JSR LOAD_ROOM
    JSR DRAW_GAME
    JSR CLOCK_RELOAD
    LDAA TICK
    STAA DRAW_LAST
    STAA MOVE_LAST
    LDAA #1
    STAA MODE
LOOP_STARTED:
    JMP FRAME_READY
GAME_INPUT:
    LDAA ACTION
    CMPA #6
    BEQ MANUAL_REWIND
    CMPA #5
    BEQ INTERACT
    CMPA #4
    BHI FRAME_READY
    LDAA PLAYER_X
    STAA CUR_X
    LDAA PLAYER_Y
    STAA CUR_Y
    LDAA ACTION
    CMPA #1
    BEQ MOVE_N
    CMPA #2
    BEQ MOVE_S
    CMPA #3
    BEQ MOVE_W
    INC CUR_X
    BRA MOVE_TEST
MOVE_N:
    DEC CUR_Y
    BRA MOVE_TEST
MOVE_S:
    INC CUR_Y
    BRA MOVE_TEST
MOVE_W:
    DEC CUR_X
MOVE_TEST:
    JSR MAP_AT
    CMPA #1
    BEQ BLOCKED
    CMPA #5
    BEQ HAZARD
    CMPA #4
    BEQ GATE
    LDAA CUR_X
    STAA PLAYER_X
    LDAA CUR_Y
    STAA PLAYER_Y
    LDX #SFX_STEP
    JSR PLAY_SFX
    JMP REDRAW
GATE:
    JSR ROOM_OPEN
    TSTA
    BEQ BLOCKED
    INC ROOM
    LDAA #1
    STAA PLAYER_X
    LDAA #4
    STAA PLAYER_Y
    JSR LOAD_ROOM
    JMP REDRAW
BLOCKED:
    LDX #SFX_EMPTY
    JSR PLAY_SFX
    JMP REDRAW
HAZARD:
    LDX #SFX_HIT
    JSR PLAY_SFX
    JMP REWIND
MANUAL_REWIND:
    LDX #SFX_REWIND
    JSR PLAY_SFX
    JMP REWIND
INTERACT:
    ; The anchor at the start jumps to the first unlit chamber.
    LDAA PLAYER_X
    CMPA #2
    BNE CHECK_SEAL
    LDAA PLAYER_Y
    CMPA #4
    BNE CHECK_SEAL
    CLR INDEX
ANCHOR_SCAN:
    LDAA INDEX
    JSR FLAG_TEST
    TSTA
    BEQ ANCHOR_GO
    INC INDEX
    LDAA INDEX
    CMPA #12
    BCS ANCHOR_SCAN
    JMP BLOCKED
ANCHOR_GO:
    LDAA INDEX
    STAA ROOM
    JSR LOAD_ROOM
    LDX #SFX_ANCHOR
    JSR PLAY_SFX
    JMP REDRAW
CHECK_SEAL:
    LDAA PLAYER_X
    SUBA #12
    BCC SEAL_X
    NEGA
SEAL_X:
    STAA VALUE
    LDAA PLAYER_Y
    SUBA #4
    BCC SEAL_Y
    NEGA
SEAL_Y:
    ADDA VALUE
    CMPA #1
    BHI BLOCKED
    JSR ROOM_OPEN
    TSTA
    BNE MANUAL_REWIND
    LDAA ROOM
    JSR FLAG_POINTER
    LDAA 0,X
    ORAA VALUE
    STAA 0,X
    LDX #SFX_SEAL
    JSR PLAY_SFX
    LDAA ROOM
    CMPA #11
    BNE REDRAW
    LDAA #3
    STAA MODE
    LDX #SFX_CLEAR
    JSR PLAY_SFX
    JSR DRAW_WIN
    JMP FRAME_READY
LOAD_ROOM:
    LDAA ROOM
    LDX #ROOM_TABLE
    JSR POINTER_INDEX
    STX SRC
    LDX #MAP
    STX DST
    LDX #160
    STX COUNT
    JMP COPY
MAP_AT:
    LDAA CUR_Y
    ASLA
    ASLA
    ASLA
    ASLA
    ADDA CUR_X
    LDX #MAP
    JSR BYTE_INDEX
    LDAA 0,X
    RTS
BYTE_INDEX:
    TAB
BYTE_LOOP:
    TSTB
    BEQ BYTE_DONE
    INX
    DECB
    BRA BYTE_LOOP
BYTE_DONE:
    RTS
FLAG_POINTER:
    TAB
    LDX #FLAGS
    CMPA #8
    BCS FLAG_LOW
    SUBB #8
    INX
FLAG_LOW:
    LDAA #1
FLAG_SHIFT:
    TSTB
    BEQ FLAG_READY
    ASLA
    DECB
    BRA FLAG_SHIFT
FLAG_READY:
    STAA VALUE
    RTS
FLAG_TEST:
    JSR FLAG_POINTER
    LDAA 0,X
    ANDA VALUE
    RTS
ROOM_OPEN:
    LDAA ROOM
    JMP FLAG_TEST
REDRAW:
    JSR DRAW_GAME
FRAME_READY:
    JMP IDLE
