TEXT_TABLE:
    STX TABLE_PTR
TEXT_TABLE_NEXT:
    LDX TABLE_PTR
    LDAA 0,X
    ORAA 1,X
    BEQ TEXT_TABLE_DONE
    LDX 0,X
    STX TEXT_OUT
    LDX TABLE_PTR
    LDX 2,X
    STX TEXT_PTR
    JSR TEXT
    LDX TABLE_PTR
    ADX #4
    STX TABLE_PTR
    BRA TEXT_TABLE_NEXT
TEXT_TABLE_DONE:
    RTS
POINTER_INDEX:
    ASLA
    TAB
POINTER_LOOP:
    TSTB
    BEQ POINTER_READ
    INX
    DECB
    BRA POINTER_LOOP
POINTER_READ:
    LDX 0,X
    RTS
DRAW_TITLE:
    LDX #TITLE_SCREEN
    STX SRC
    LDX #FRAMEBUFFER
    STX DST
    LDX #768
    STX COUNT
    JSR COPY
    LDX #TITLE_TEXT
    JSR TEXT_TABLE
    JMP PRESENT
DRAW_HELP:
    JSR CLEAR_SCREEN
    LDX #HELP_TEXT
    JSR TEXT_TABLE
    JMP PRESENT
DRAW_GAME:
    JSR CLEAR_SCREEN
    LDX #HUD_TEXT
    JSR TEXT_TABLE
    LDAA LEVEL
    INCA
    LDX #FRAMEBUFFER + 26
    JSR NUMBER
    LDAA TARGETS
    LDX #FRAMEBUFFER + 32 * 3 + 27
    JSR NUMBER
    LDAA MARKED
    LDX #FRAMEBUFFER + 32 * 6 + 27
    JSR NUMBER
    LDAA PATH_LEN
    LDX #FRAMEBUFFER + 32 * 9 + 27
    JSR NUMBER
    LDAA COMBO
    LDX #FRAMEBUFFER + 32 * 12 + 27
    JSR NUMBER
    LDAA #$9C
    LDX #FRAMEBUFFER + 32
    LDAB #32
DRAW_BAR:
    STAA 0,X
    INX
    DECB
    BNE DRAW_BAR
    LDX #FRAMEBUFFER + 32 * 21
    LDAB #32
DRAW_BOTTOM:
    STAA 0,X
    INX
    DECB
    BNE DRAW_BOTTOM
    CLR INDEX
    CLR DRAW_Y
    LDX #FRAMEBUFFER + 32 * 3
    STX DRAW_PTR
DRAW_ROW:
    CLR DRAW_X
DRAW_CELL:
    LDAA INDEX
    LDX #MAP
    JSR BYTE_INDEX
    LDAA 0,X
    BEQ DRAW_FLOOR
    DECA
    ASLA
    ASLA
    ADDA #$80
    ; Exit follows the player glyphs in the bank.
    CMPA #$88
    BNE DRAW_ACTOR
    LDAA #$8C
    BRA DRAW_ACTOR
DRAW_FLOOR:
    LDAA INDEX
    LDX #VISITED
    JSR BYTE_INDEX
    LDAA 0,X
    BEQ DRAW_GRID
    LDAA #$90
    BRA DRAW_ACTOR
DRAW_GRID:
    LDAA #$98
DRAW_ACTOR:
    STAA DRAW_TILE
    CMPA #$84
    BNE DRAW_CURSOR
    LDAA INDEX
    LDX #VISITED
    JSR BYTE_INDEX
    TST 0,X
    BEQ DRAW_CURSOR
    LDAA #$94
    STAA DRAW_TILE
DRAW_CURSOR:
    LDAA DRAW_X
    CMPA PLAYER_X
    BNE DRAW_TILE_READY
    LDAA DRAW_Y
    CMPA PLAYER_Y
    BNE DRAW_TILE_READY
    LDAA #$88
    STAA DRAW_TILE
DRAW_TILE_READY:
    LDX DRAW_PTR
    LDAA DRAW_TILE
    STAA 0,X
    INCA
    STAA 1,X
    INCA
    STAA 32,X
    INCA
    STAA 33,X
    INX
    INX
    STX DRAW_PTR
    INC INDEX
    INC DRAW_X
    LDAA DRAW_X
    CMPA #12
    BCS DRAW_CELL
    LDX DRAW_PTR
    ADX #40
    STX DRAW_PTR
    JSR CLOCK_SERVICE
    INC DRAW_Y
    LDAA DRAW_Y
    CMPA #9
    BCS DRAW_ROW
    LDAA MODE
    CMPA #2
    BEQ DRAW_MENU
    CMPA #3
    BEQ DRAW_EXEC_TEXT
    CMPA #4
    BEQ DRAW_CLEAR_TEXT
    TST ERROR
    BEQ DRAW_PRESENT
    LDX #ERROR_TEXT
    BRA DRAW_STATUS
DRAW_EXEC_TEXT:
    LDX #EXEC_TEXT
    BRA DRAW_STATUS
DRAW_CLEAR_TEXT:
    LDX #CLEAR_TEXT
DRAW_STATUS:
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 32 * 22
    STX TEXT_OUT
    JSR TEXT
DRAW_PRESENT:
    JMP PRESENT
DRAW_MENU:
    CLR INDEX
    LDX #FRAMEBUFFER + 32 * 15 + 27
    STX DRAW_PTR
DRAW_MENU_ROW:
    LDAA INDEX
    LDX #MENU_NAMES
    JSR POINTER_INDEX
    STX TEXT_PTR
    LDX DRAW_PTR
    STX TEXT_OUT
    JSR TEXT
    LDAA INDEX
    CMPA MENU
    BNE DRAW_MENU_NEXT
    LDX DRAW_PTR
    DEX
    DEX
    LDAA #30
    STAA 0,X
DRAW_MENU_NEXT:
    LDX DRAW_PTR
    ADX #32
    STX DRAW_PTR
    INC INDEX
    LDAA INDEX
    CMPA #5
    BCS DRAW_MENU_ROW
    JMP PRESENT
DRAW_WIN:
    JSR CLEAR_SCREEN
    LDX #FRAMEBUFFER + 32 * 3
    LDAB #32
    LDAA #$9C
WIN_BORDER:
    STAA 0,X
    INX
    DECB
    BNE WIN_BORDER
    LDX #FRAMEBUFFER + 32 * 21
    LDAB #32
WIN_BORDER_BOTTOM:
    STAA 0,X
    INX
    DECB
    BNE WIN_BORDER_BOTTOM
    LDX #WIN_TEXT
    JSR TEXT_TABLE
    JMP PRESENT
