GAME_START:
SHOW_TITLE:
    CLR MODE
    LDX #TITLE_PCG
    JSR LOAD_PCG
    LDX #MUSIC_TITLE
    JSR PLAY_MUSIC
    JSR DRAW_TITLE
    JMP FRAME_READY
IDLE:
    JSR CLOCK_SERVICE
    LDAA MODE
    CMPA #3
    BNE INPUT_IDLE
    JSR EXEC_TICK
INPUT_IDLE:
    JSR INPUT_CAPTURE
    LDAA KEY_PENDING
    BEQ IDLE
    CLR KEY_PENDING
DISPATCH:
    STAA ACTION
    LDAA MODE
    BEQ TITLE_INPUT
    CMPA #1
    BEQ PLAN_INPUT
    CMPA #2
    BEQ MENU_INPUT
    CMPA #4
    BEQ NEXT_LEVEL
    CMPA #3
    BEQ FRAME_READY
    JMP SHOW_TITLE
TITLE_INPUT:
    LDAA ACTION
    CMPA #5
    BEQ NEW_GAME
    LDAA #6
    STAA MODE
    JSR DRAW_HELP
    JMP FRAME_READY
NEW_GAME:
    CLR LEVEL
    JSR SOUND_STOP
    LDX #GAME_PCG
    JSR LOAD_PCG
LOAD_LEVEL:
    JSR QUEUE_START
    LDAA LEVEL
    LDX #LEVEL_TABLE
    JSR POINTER_INDEX
    STX SRC
    LDX #MAP
    STX DST
    LDX #108
    STX COUNT
    JSR COPY
    CLR TARGETS
    LDX #MAP
    LDAB #108
COUNT_TARGETS:
    LDAA 0,X
    CMPA #2
    BNE COUNT_NEXT
    INC TARGETS
COUNT_NEXT:
    INX
    DECB
    BNE COUNT_TARGETS
RESET_PATH:
    LDX #VISITED
    LDAB #108
CLEAR_VISITED:
    CLR 0,X
    INX
    DECB
    BNE CLEAR_VISITED
    LDAA #1
    STAA PLAYER_X
    STAA PLAYER_Y
    STAA VISITED + 13
    STAA MODE
    LDAA #13
    STAA PATH
    CLR PATH_LEN
    CLR MARKED
    CLR COMBO
    CLR ERROR
    JMP REDRAW
PLAN_INPUT:
    LDAA ACTION
    CMPA #5
    BEQ OPEN_MENU
    CMPA #6
    BEQ UNDO
    CMPA #8
    BEQ EXECUTE
    CMPA #4
    BHI FRAME_READY
    LDAA PLAYER_X
    STAA CUR_X
    LDAA PLAYER_Y
    STAA CUR_Y
    LDAA ACTION
    CMPA #1
    BEQ NORTH
    CMPA #2
    BEQ SOUTH
    CMPA #3
    BEQ WEST
    INC CUR_X
    BRA ADD_STEP
NORTH:
    DEC CUR_Y
    BRA ADD_STEP
SOUTH:
    INC CUR_Y
    BRA ADD_STEP
WEST:
    DEC CUR_X
ADD_STEP:
    JSR POSITION
    LDX #MAP
    JSR BYTE_INDEX
    LDAA 0,X
    CMPA #1
    BEQ INVALID
    LDX #VISITED
    LDAA CUR_POS
    JSR BYTE_INDEX
    TST 0,X
    BNE INVALID
    LDAA #1
    STAA 0,X
    INC PATH_LEN
    LDAA PATH_LEN
    LDX #PATH
    JSR BYTE_INDEX
    LDAA CUR_POS
    STAA 0,X
    LDX #MAP
    JSR BYTE_INDEX
    LDAA 0,X
    CMPA #2
    BNE MOVE_CURSOR
    INC MARKED
MOVE_CURSOR:
    LDAA CUR_X
    STAA PLAYER_X
    LDAA CUR_Y
    STAA PLAYER_Y
    CLR ERROR
    LDX #SFX_STEP
    JSR PLAY_SFX
    JMP REDRAW
INVALID:
    LDAA #1
    STAA ERROR
    LDX #SFX_EMPTY
    JSR PLAY_SFX
    JMP REDRAW
UNDO:
    TST PATH_LEN
    BEQ INVALID
    LDAA PATH_LEN
    LDX #PATH
    JSR BYTE_INDEX
    LDAA 0,X
    STAA CUR_POS
    LDX #VISITED
    JSR BYTE_INDEX
    CLR 0,X
    LDAA CUR_POS
    LDX #MAP
    JSR BYTE_INDEX
    LDAA 0,X
    CMPA #2
    BNE UNDO_POSITION
    DEC MARKED
UNDO_POSITION:
    DEC PATH_LEN
    LDAA PATH_LEN
    LDX #PATH
    JSR BYTE_INDEX
    LDAA 0,X
    JSR DECODE_POSITION
    LDAA CUR_X
    STAA PLAYER_X
    LDAA CUR_Y
    STAA PLAYER_Y
    LDAA #1
    STAA MODE
    CLR ERROR
    LDX #SFX_UNDO
    JSR PLAY_SFX
    JMP REDRAW
OPEN_MENU:
    LDAA #2
    STAA MODE
    CLR MENU
    JMP REDRAW
MENU_INPUT:
    LDAA ACTION
    CMPA #1
    BEQ MENU_UP
    CMPA #2
    BEQ MENU_DOWN
    CMPA #6
    BEQ CLOSE_MENU
    CMPA #5
    BNE FRAME_READY
    LDAA MENU
    BEQ EXECUTE
    CMPA #1
    BEQ UNDO
    CMPA #2
    BEQ REQUEST_RESET
    CMPA #3
    BEQ REQUEST_TITLE
CLOSE_MENU:
    LDAA #1
    STAA MODE
    JMP REDRAW
MENU_UP:
    DEC MENU
    BPL REDRAW
    LDAA #4
    STAA MENU
    JMP REDRAW
MENU_DOWN:
    INC MENU
    LDAA MENU
    CMPA #5
    BCS REDRAW
    CLR MENU
    JMP REDRAW
EXECUTE:
    LDAA MARKED
    CMPA TARGETS
    BNE INVALID
    LDAA PLAYER_X
    STAA CUR_X
    LDAA PLAYER_Y
    STAA CUR_Y
    JSR POSITION
    LDX #MAP
    JSR BYTE_INDEX
    LDAA 0,X
    CMPA #3
    BNE INVALID
    CLR EXEC_POS
    CLR COMBO
    LDAA #1
    STAA PLAYER_X
    STAA PLAYER_Y
    LDAA #3
    STAA MODE
    LDAA TICK
    STAA ANIM_LAST
    JMP REDRAW
EXEC_TICK:
    LDAA TICK
    SUBA ANIM_LAST
    CMPA #5
    BCS EXEC_DONE
    LDAA TICK
    STAA ANIM_LAST
    INC EXEC_POS
    LDAA EXEC_POS
    LDX #PATH
    JSR BYTE_INDEX
    LDAA 0,X
    STAA CUR_POS
    JSR DECODE_POSITION
    LDAA PLAYER_X
    LDAB PLAYER_Y
    JSR FX_AT
    LDAA #4
    LDAB CUR_X
    CMPB PLAYER_X
    BHI TRACE_STEP_READY
    LDAA #3
    BCS TRACE_STEP_READY
    LDAA #2
    LDAB CUR_Y
    CMPB PLAYER_Y
    BHI TRACE_STEP_READY
    LDAA #1
TRACE_STEP_READY:
    JSR FX_MOVE
    LDAA CUR_X
    STAA PLAYER_X
    LDAA CUR_Y
    STAA PLAYER_Y
    LDAA CUR_POS
    LDX #MAP
    JSR BYTE_INDEX
    LDAA 0,X
    CMPA #2
    BNE EXEC_CHECK
    CLR 0,X
    LDAA CUR_X
    LDAB CUR_Y
    JSR FX_AT
    JSR FX_BURST
    INC COMBO
    LDX #SFX_CUT
    JSR PLAY_SFX
EXEC_CHECK:
    LDAA EXEC_POS
    CMPA PATH_LEN
    BNE EXEC_DRAW
    LDAA #4
    STAA MODE
    JSR QUEUE_CLEAR
EXEC_DRAW:
    JSR DRAW_GAME
EXEC_DONE:
    RTS
NEXT_LEVEL:
    INC LEVEL
    LDAA LEVEL
    CMPA #30
    BCS LOAD_LEVEL
    LDAA #5
    STAA MODE
    JSR DRAW_WIN
    JMP FRAME_READY
POSITION:
    LDAA CUR_Y
    ASLA
    ASLA
    STAA CUR_POS
    ASLA
    ADDA CUR_POS
    ADDA CUR_X
    STAA CUR_POS
    RTS
BYTE_INDEX:
    TAB
BYTE_LOOP:
    TSTB
    BEQ BYTE_DONE
    INX
    DECB
    BRA BYTE_LOOP
BYTE_DONE:
    RTS
DECODE_POSITION:
    CLR CUR_Y
DECODE_ROW:
    CMPA #12
    BCS DECODE_COL
    SUBA #12
    INC CUR_Y
    BRA DECODE_ROW
DECODE_COL:
    STAA CUR_X
    RTS
REDRAW:
    JSR DRAW_GAME
FRAME_READY:
    JMP IDLE

REQUEST_RESET:
    JSR CONFIRM_RESET
    TSTA
    BEQ REDRAW
    JMP RESET_PATH
REQUEST_TITLE:
    JSR CONFIRM_RESET
    TSTA
    BEQ REDRAW
    JMP SHOW_TITLE
