; Destructive restart confirmation. The caller redraws its view after cancel.
; No gameplay dispatch runs here; restore the game tick on return.
CN_ACTIVE: .equ $3330
CN_CHOICE: .equ $3331
CN_TICK: .equ $3332
CN_FONT: .equ $3333
CONFIRM_RESET:
    LDAA TICK
    STAA CN_TICK
    LDAA #1
    STAA CN_ACTIVE
    CLR CN_CHOICE
CONFIRM_DRAW:
    LDX #FRAMEBUFFER + 9 * 32
    LDAA #64
    LDAB #160
CONFIRM_BLANK:
    STAA 0,X
    INX
    DECB
    BNE CONFIRM_BLANK
    LDX #CONFIRM_QUESTION
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 10 * 32 + 9
    STX TEXT_OUT
    JSR TEXT
    LDX #CONFIRM_CHOICES
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 11 * 32 + 10
    STX TEXT_OUT
    JSR TEXT
    LDX #FRAMEBUFFER + 11 * 32 + 9
    TST CN_CHOICE
    BEQ CONFIRM_CURSOR
    LDX #FRAMEBUFFER + 11 * 32 + 17
CONFIRM_CURSOR:
    LDAA #30
    STAA 0,X
    LDX #CONFIRM_HINT
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 13 * 32 + 2
    STX TEXT_OUT
    JSR TEXT
    JSR PRESENT
CONFIRM_READY:
    JMP CONFIRM_IDLE
CONFIRM_IDLE:
    JSR CLOCK_SERVICE
    JSR INPUT_CAPTURE
    LDAA KEY_PENDING
    BEQ CONFIRM_IDLE
CONFIRM_DISPATCH:
    CLR KEY_PENDING
    CMPA #6
    BEQ CONFIRM_NO
    CMPA #5
    BEQ CONFIRM_DONE
    CMPA #4
    BHI CONFIRM_READY
    DECA
    ANDA #1
    STAA CN_CHOICE
    JMP CONFIRM_DRAW
CONFIRM_NO:
    CLR CN_CHOICE
CONFIRM_DONE:
    CLR CN_ACTIVE
    CLR KEY_PENDING
    JSR CLOCK_RELOAD
    LDAA CN_TICK
    STAA TICK
    LDAA CN_CHOICE
    RTS
CONFIRM_QUESTION:
    .byte "REALLY RESET?",0
CONFIRM_CHOICES:
    .byte "NO      YES",0
CONFIRM_HINT:
    .byte "A/D SELECT  RETURN CHOOSE",0
