; Presentation-only time. Sound/input are polled, gameplay is never dispatched.
INTRO_PENDING: .equ $3390
PACE_ACTIVE: .equ $3391
INTRO_PHASE: .equ $3392
PACE_LENGTH: .equ $3393
PACE_BEGIN: .equ $3394
PACE_CLOCK: .equ $3395
LOSS_MESSAGE: .equ $3396
IMPACT_CELL: .equ $3398
IMPACT_PHASE: .equ $339A
IMPACT_PENDING: .equ $339B

QUEUE_START:
    LDAA #1
    STAA INTRO_PENDING
    CLR IMPACT_PENDING
    LDX #FAILURE_TEXT
    STX LOSS_MESSAGE
    RTS

PACE_WAIT:
    STAA PACE_LENGTH
    LDAA TICK
    STAA PACE_BEGIN
PACE_WAIT_LOOP:
    JSR CLOCK_SERVICE
    CLR KEY_PENDING
    LDAA TICK
    SUBA PACE_BEGIN
    CMPA PACE_LENGTH
    BCS PACE_WAIT_LOOP
    CLR KEY_ACTION
    RTS

; Filter only actor slots during the reveal; all ROM labels remain readable.
INTRO_FILTER:
    TST INTRO_PHASE
    BEQ INTRO_FILTER_DONE
    CMPA #128
    BCS INTRO_FILTER_DONE
    CMPA #160
    BCC INTRO_FILTER_DONE
    PSHB
    PSHA
    SUBA #128
    STAA VALUE
    LDX #INTRO_GROUPS
INTRO_INDEX:
    TSTA
    BEQ INTRO_LOOKUP
    INX
    DECA
    BRA INTRO_INDEX
INTRO_LOOKUP:
    LDAA INTRO_PHASE
    CMPA 0,X
    PULA
    BCC INTRO_VISIBLE
    LDAA #64
INTRO_VISIBLE:
    PULB
INTRO_FILTER_DONE:
    RTS

INTRO_SCENE:
    CLR INTRO_PENDING
    INC PACE_ACTIVE
    LDAA TICK
    STAA PACE_CLOCK
    LDAA #1
    STAA INTRO_PHASE
INTRO_REVEAL:
    JSR PRESENT_ROWS
    LDX #INTRO_NOTE
    JSR PLAY_SFX
    LDAA #12
    JSR PACE_WAIT
    INC INTRO_PHASE
    LDAA INTRO_PHASE
    CMPA #INTRO_STEPS + 1
    BCS INTRO_REVEAL
    CLR INTRO_PHASE
    LDX #$C100 + 10 * 32 + 8
    LDAA #3
    STAA VALUE
INTRO_BANNER_ROW:
    LDAB #16
    LDAA #64
INTRO_BANNER_CELL:
    STAA 0,X
    INX
    DECB
    BNE INTRO_BANNER_CELL
    ADX #16
    DEC VALUE
    BNE INTRO_BANNER_ROW
    LDX #START_MESSAGE
    STX SRC
    LDX #$C100 + 11 * 32 + 8
    STX DST
    LDX #16
    STX COUNT
    JSR COPY
INTRO_MESSAGE_VISIBLE:
    LDX #START_NOTE
    JSR PLAY_SFX
    LDAA #42
    JSR PACE_WAIT
    JSR PRESENT_ROWS
    CLR PACE_ACTIVE
    LDAA PACE_CLOCK
    STAA TICK
    RTS

QUEUE_IMPACT:
    STX IMPACT_CELL
    LDAA #1
    STAA IMPACT_PENDING
    RTS

SCENE_IMPACT:
    CLR IMPACT_PENDING
    LDAA TICK
    STAA PACE_CLOCK
    INC PACE_ACTIVE
    LDX #IMPACT_NOTE
    JSR PLAY_SFX
    LDAA #2
    STAA IMPACT_PHASE
SCENE_IMPACT_FLASH:
    LDX IMPACT_CELL
    LDAA #$4E
    STAA 0,X
    STAA 1,X
    STAA 32,X
    STAA 33,X
    LDAA #4
    JSR PACE_WAIT
    JSR PRESENT_ROWS
    LDAA #4
    JSR PACE_WAIT
    DEC IMPACT_PHASE
    BNE SCENE_IMPACT_FLASH
    CLR PACE_ACTIVE
    LDAA PACE_CLOCK
    STAA TICK
    RTS
