TEXT_TABLE:
    STX TABLE_PTR
TEXT_TABLE_NEXT:
    LDX TABLE_PTR
    LDAA 0,X
    ORAA 1,X
    BEQ TEXT_TABLE_DONE
    LDX 0,X
    STX TEXT_OUT
    LDX TABLE_PTR
    LDX 2,X
    STX TEXT_PTR
    JSR TEXT
    LDX TABLE_PTR
    ADX #4
    STX TABLE_PTR
    BRA TEXT_TABLE_NEXT
TEXT_TABLE_DONE:
    RTS
POINTER_INDEX:
    ASLA
    TAB
POINTER_LOOP:
    TSTB
    BEQ POINTER_READ
    INX
    DECB
    BRA POINTER_LOOP
POINTER_READ:
    LDX 0,X
    RTS
DRAW_TITLE:
    LDX #TITLE_SCREEN
    STX SRC
    LDX #FRAMEBUFFER
    STX DST
    LDX #768
    STX COUNT
    JSR COPY
    LDX #TITLE_TEXT
    JSR TEXT_TABLE
    JMP PRESENT
DRAW_HELP:
    JSR CLEAR_SCREEN
    LDX #HELP_TEXT
    JSR TEXT_TABLE
    JMP PRESENT
DRAW_PHOTO:
    JSR CLEAR_SCREEN
    LDAA PHOTO
    LDX #SITE_NAMES
    JSR POINTER_INDEX
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 34
    STX TEXT_OUT
    JSR TEXT
    LDAA PHOTO
    LDX #PHOTO_TABLE
    JSR POINTER_INDEX
    STX SRC
    LDX #FRAMEBUFFER + 96
    STX DST
PHOTO_RUN:
    LDX SRC
    LDAB 0,X
    BEQ PHOTO_DONE
    LDAA 1,X
    INX
    INX
    STX SRC
    LDX DST
PHOTO_CELL:
    STAA 0,X
    INX
    DECB
    BNE PHOTO_CELL
    STX DST
    JSR CLOCK_SERVICE
    BRA PHOTO_RUN
PHOTO_DONE:
    LDX #PHOTO_TEXT
    JSR TEXT_TABLE
    JMP PRESENT
DRAW_NAV:
    JSR CLEAR_SCREEN
    LDAA MODE
    CMPA #4
    BEQ DRAW_LOST
    CMPA #5
    BEQ DRAW_WIN
    LDX #HUD_TEXT
    JSR TEXT_TABLE
    JSR DRAW_INSTRUMENTS
    LDAA PLAYER_X
    SUBA #4
    BCC VIEW_X_HIGH
    CLRA
VIEW_X_HIGH:
    CMPA #22
    BLS VIEW_X_STORE
    LDAA #22
VIEW_X_STORE:
    STAA VIEW_X
    LDAA PLAYER_Y
    SUBA #4
    BCC VIEW_Y_HIGH
    CLRA
VIEW_Y_HIGH:
    CMPA #23
    BLS VIEW_Y_STORE
    LDAA #23
VIEW_Y_STORE:
    STAA VIEW_Y
    LDAA #2
    TST SIGHT
    BEQ VIEW_RADIUS
    LDAA #6
VIEW_RADIUS:
    STAA RADIUS
    CLR DRAW_Y
    LDX #FRAMEBUFFER + 64
    STX DRAW_PTR
MAP_DRAW_ROW:
    CLR DRAW_X
MAP_DRAW_CELL:
    LDAA DRAW_X
    ADDA VIEW_X
    STAA CUR_X
    LDAA DRAW_Y
    ADDA VIEW_Y
    STAA CUR_Y
    JSR DIST_FROM_PLAYER
    CMPA RADIUS
    BHI DRAW_FOG
    JSR MAP_AT
    CMPA #1
    BEQ DRAW_ROCK
    CMPA #6
    BCC DRAW_SITE
    CMPA #2
    BCC DRAW_CURRENT
    LDAA #$40
    BRA DRAW_ACTORS
DRAW_FOG:
    LDAA #$90
    BRA DRAW_CELL
DRAW_ROCK:
    LDAA #$84
    BRA DRAW_ACTORS
DRAW_SITE:
    LDAA #$88
    BRA DRAW_ACTORS
DRAW_CURRENT:
    LDAA #$94
DRAW_ACTORS:
    STAA DRAW_TILE
    LDAA CUR_X
    CMPA HUNTER_X
    BNE DRAW_PLAYER
    LDAA CUR_Y
    CMPA HUNTER_Y
    BNE DRAW_PLAYER
    LDAA #$8C
    STAA DRAW_TILE
DRAW_PLAYER:
    LDAA CUR_X
    CMPA PLAYER_X
    BNE DRAW_TILE_READY
    LDAA CUR_Y
    CMPA PLAYER_Y
    BNE DRAW_TILE_READY
    LDAA #$80
    STAA DRAW_TILE
DRAW_TILE_READY:
    LDAA DRAW_TILE
DRAW_CELL:
    STAA DRAW_TILE
    LDX DRAW_PTR
    STAA 0,X
    CMPA #$40
    BEQ DRAW_BLANK
    INCA
    STAA 1,X
    INCA
    STAA 32,X
    INCA
    STAA 33,X
    BRA DRAW_ADVANCE
DRAW_BLANK:
    STAA 1,X
    STAA 32,X
    STAA 33,X
DRAW_ADVANCE:
    LDAA DRAW_TILE
    CMPA #$94
    BNE DRAW_CELL_NEXT
    JSR MAP_AT
    SUBA #2
    TAB
    LDX #CURRENT_LETTERS
DRAW_CURRENT_INDEX:
    TSTB
    BEQ DRAW_CURRENT_LETTER
    INX
    DECB
    BRA DRAW_CURRENT_INDEX
DRAW_CURRENT_LETTER:
    LDAA 0,X
    LDX DRAW_PTR
    STAA 33,X
DRAW_CELL_NEXT:
    LDX DRAW_PTR
    INX
    INX
    STX DRAW_PTR
    INC DRAW_X
    LDAA DRAW_X
    CMPA #10
    BCS MAP_DRAW_CELL
    LDX DRAW_PTR
    ADX #44
    STX DRAW_PTR
    JSR CLOCK_SERVICE
    INC DRAW_Y
    LDAA DRAW_Y
    CMPA #9
    BCS MAP_DRAW_ROW
    LDAA MODE
    CMPA #2
    BNE NAV_PRESENT
    JSR DRAW_MENU
NAV_PRESENT:
    JMP PRESENT
DRAW_INSTRUMENTS:
    LDX #FRAMEBUFFER + 32
    LDAB #32
    LDAA #$9C
HUD_LINES:
    STAA 0,X
    INX
    DECB
    BNE HUD_LINES
    ; Vertical divider separates the sonar from the instrument column.
    LDX #FRAMEBUFFER + 64 + 20
    LDAB #18
    LDAA #$9D
HUD_DIVIDER:
    STAA 0,X
    ADX #32
    DECB
    BNE HUD_DIVIDER
    LDX #FRAMEBUFFER + 640
    LDAB #32
    LDAA #$9C
HUD_BOTTOM:
    STAA 0,X
    INX
    DECB
    BNE HUD_BOTTOM
    LDAA OXYGEN
    LDX #FRAMEBUFFER + 3
    JSR NUMBER
    LDAA OXYGEN
    CMPA #30
    BHI OXYGEN_BAR_INIT
    LDAB #1
    STAB FRAMEBUFFER + 19
    STAB FRAMEBUFFER + 20
    STAB FRAMEBUFFER + 21
OXYGEN_BAR_INIT:
    LDAB #0
OXYGEN_BAR_COUNT:
    SUBA #20
    BCS OXYGEN_BAR_DRAW
    INCB
    BRA OXYGEN_BAR_COUNT
OXYGEN_BAR_DRAW:
    LDX #FRAMEBUFFER + 7
    LDAA #$9E
OXYGEN_BAR:
    TSTB
    BEQ DRAW_HULL
    STAA 0,X
    INX
    DECB
    BRA OXYGEN_BAR
DRAW_HULL:
    LDX #FRAMEBUFFER + 27
    LDAB HULL
    LDAA #$9F
HULL_ICON:
    TSTB
    BEQ DRAW_DEPTH
    STAA 0,X
    INX
    DECB
    BRA HULL_ICON
DRAW_DEPTH:
    LDAA PLAYER_Y
    ASLA
    ADDA PLAYER_Y
    ADDA #10
    LDX #FRAMEBUFFER + 32 * 6 + 23
    JSR NUMBER
    JSR GET_TARGET
    LDAA DISTANCE
    LDX #FRAMEBUFFER + 32 * 9 + 23
    JSR NUMBER
    LDAA BEARING
    LDX #BEARING_NAMES
    JSR POINTER_INDEX
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 32 * 11 + 23
    STX TEXT_OUT
    JSR TEXT
    LDAA TARGET
    LDX #SITE_NAMES
    JSR POINTER_INDEX
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 32 * 21 + 4
    STX TEXT_OUT
    JSR TEXT
    TST STATUS
    BEQ DRAW_SAMPLE_COUNT
    LDX #NONE_TEXT
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 32 * 21 + 3
    STX TEXT_OUT
    JSR TEXT
DRAW_SAMPLE_COUNT:
    LDAA SAMPLES
    LDX #FRAMEBUFFER + 32 * 13 + 22
    JSR NUMBER
    LDX #CRUISE_TEXT
    TST QUIET
    BEQ DRAW_ENGINE
    LDX #QUIET_TEXT
DRAW_ENGINE:
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 32 * 16 + 22
    STX TEXT_OUT
    JSR TEXT
    LDX #READY_TEXT
    TST SIGHT
    BEQ DRAW_SONAR_STATE
    LDX #ACTIVE_TEXT
DRAW_SONAR_STATE:
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 32 * 19 + 22
    STX TEXT_OUT
    JSR TEXT
    LDAA HUNTER_X
    STAA CUR_X
    LDAA HUNTER_Y
    STAA CUR_Y
    JSR DIST_FROM_PLAYER
    LDX #CLEAR_TEXT
    CMPA #6
    BHI DRAW_CONTACT
    LDX #CONTACT_TEXT
DRAW_CONTACT:
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 32 * 17 + 22
    STX TEXT_OUT
    JMP TEXT
DRAW_MENU:
    LDX #FRAMEBUFFER + 32 * 5 + 1
    LDAB #14
MENU_CLEAR_ROW:
    STAB DRAW_Y
    LDAB #18
    LDAA #$40
MENU_CLEAR_CELL:
    STAA 0,X
    INX
    DECB
    BNE MENU_CLEAR_CELL
    ADX #14
    LDAB DRAW_Y
    DECB
    BNE MENU_CLEAR_ROW
    LDX #MENU_TEXT
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 32 * 5 + 3
    STX TEXT_OUT
    JSR TEXT
    CLR INDEX
    LDX #FRAMEBUFFER + 32 * 7 + 4
    STX DRAW_PTR
MENU_DRAW_ITEM:
    LDAA INDEX
    LDX #MENU_NAMES
    JSR POINTER_INDEX
    STX TEXT_PTR
    LDX DRAW_PTR
    STX TEXT_OUT
    JSR TEXT
    LDAA INDEX
    CMPA MENU
    BNE MENU_DRAW_NEXT
    LDX DRAW_PTR
    DEX
    DEX
    LDAA #30
    STAA 0,X
MENU_DRAW_NEXT:
    LDX DRAW_PTR
    ADX #64
    STX DRAW_PTR
    INC INDEX
    LDAA INDEX
    CMPA #6
    BCS MENU_DRAW_ITEM
    RTS
DRAW_LOST:
    LDX #LOST_TEXT
    JSR TEXT_TABLE
    LDAA SAMPLES
    LDX #FRAMEBUFFER + 32 * 13 + 14
    JSR NUMBER
    JMP PRESENT
DRAW_WIN:
    LDX #WIN_TEXT
    JSR TEXT_TABLE
    LDAA OXYGEN
    LDX #FRAMEBUFFER + 32 * 16 + 14
    JSR NUMBER
    JMP PRESENT

CURRENT_LETTERS:
    .byte 37,51,55,46
