GAME_START:
SHOW_TITLE:
    CLR MODE
    LDX #TITLE_PCG
    JSR LOAD_PCG
    LDX #MUSIC_TITLE
    JSR PLAY_MUSIC
    JSR DRAW_TITLE
    JMP FRAME_READY
IDLE:
    JSR CLOCK_SERVICE
    JSR INPUT_CAPTURE
    LDAA KEY_PENDING
    BEQ IDLE
    CLR KEY_PENDING
DISPATCH:
    STAA ACTION
    LDAA MODE
    BEQ TITLE_INPUT
    CMPA #1
    BEQ NAV_INPUT
    CMPA #2
    BEQ MENU_INPUT
    CMPA #3
    BEQ PHOTO_INPUT
    CMPA #4
    BEQ LOST_INPUT
    JMP SHOW_TITLE
TITLE_INPUT:
    LDAA ACTION
    CMPA #5
    BEQ NEW_MISSION
    LDAA #6
    STAA MODE
    JSR DRAW_HELP
    JMP FRAME_READY
NEW_MISSION:
    JSR SOUND_STOP
    CLR SAMPLES
    CLR FLAGS
    CLR TARGET
    CLR SIGHT
    CLR NOISE
    CLR QUIET
    CLR TURN
    CLR GRACE
    CLR STATUS
    LDAA #2
    STAA PLAYER_X
    STAA PLAYER_Y
    LDAA #220
    STAA OXYGEN
    LDAA #5
    STAA HULL
    LDAA #22
    STAA HUNTER_X
    LDAA #16
    STAA HUNTER_Y
    LDX #WORLD_MAP
    STX SRC
    LDX #MAP
    STX DST
    LDX #1024
    STX COUNT
    JSR COPY
RETURN_NAV:
    LDAA #1
    STAA MODE
    LDX #GAME_PCG
    JSR LOAD_PCG
    JMP REDRAW
NAV_INPUT:
    LDAA ACTION
    CMPA #5
    BEQ OPEN_MENU
    CMPA #6
    BEQ OPEN_MENU
    CMPA #8
    BEQ SONAR
    JSR NAVIGATE
    JMP REDRAW
OPEN_MENU:
    LDAA #2
    STAA MODE
    CLR MENU
    LDX #SFX_MENU
    JSR PLAY_SFX
    JMP REDRAW
MENU_INPUT:
    LDX #SFX_MENU
    JSR PLAY_SFX
    LDAA ACTION
    CMPA #1
    BEQ MENU_UP
    CMPA #2
    BEQ MENU_DOWN
    CMPA #6
    BEQ RETURN_NAV
    CMPA #5
    BNE IDLE
    LDAA MENU
    BEQ SONAR
    CMPA #1
    BEQ RECORD_SITE
    CMPA #2
    BEQ TOGGLE_QUIET
    CMPA #3
    BEQ MENU_WAIT
    CMPA #4
    BEQ REQUEST_RESET
    JMP REQUEST_TITLE
MENU_UP:
    DEC MENU
    BPL REDRAW
    LDAA #5
    STAA MENU
    JMP REDRAW
MENU_DOWN:
    INC MENU
    LDAA MENU
    CMPA #6
    BCS REDRAW
    CLR MENU
    JMP REDRAW
MENU_WAIT:
    LDAA #1
    STAA MODE
    LDAA #7
    STAA ACTION
    JSR NAVIGATE
    JMP REDRAW
TOGGLE_QUIET:
    LDAA QUIET
    EORA #1
    STAA QUIET
    JMP RETURN_NAV
SONAR:
    LDAA #1
    STAA MODE
    LDAA #7
    STAA SIGHT
    LDAA #9
    STAA NOISE
    LDAA #2
    JSR SPEND_OXYGEN
    LDX #SFX_SONAR
    JSR PLAY_SFX
    JSR WORLD_STEP
    JMP REDRAW
RECORD_SITE:
    LDAA #1
    STAA MODE
    CLR INDEX
RECORD_SCAN:
    LDX #SITE_X
    LDAB INDEX
RECORD_X_INDEX:
    TSTB
    BEQ RECORD_X
    INX
    DECB
    BRA RECORD_X_INDEX
RECORD_X:
    LDAA 0,X
    STAA CUR_X
    LDX #SITE_Y
    LDAB INDEX
RECORD_Y_INDEX:
    TSTB
    BEQ RECORD_Y
    INX
    DECB
    BRA RECORD_Y_INDEX
RECORD_Y:
    LDAA 0,X
    STAA CUR_Y
    JSR DIST_FROM_PLAYER
    CMPA #1
    BHI RECORD_NEXT
    LDX #BIT_MASKS
    LDAB INDEX
RECORD_FLAG_INDEX:
    TSTB
    BEQ RECORD_FLAG
    INX
    DECB
    BRA RECORD_FLAG_INDEX
RECORD_FLAG:
    LDAA 0,X
    BITA FLAGS
    BNE RECORD_NEXT
    ORAA FLAGS
    STAA FLAGS
    LDAA INDEX
    STAA PHOTO
    INC SAMPLES
    LDAA #2
    JSR SPEND_OXYGEN
    JSR WORLD_STEP
    LDAA MODE
    CMPA #1
    BNE REDRAW
    LDAA #3
    STAA MODE
    LDX #SFX_RECORD
    JSR PLAY_SFX
    LDX #TITLE_PCG
    JSR LOAD_PCG
    JSR DRAW_PHOTO
    JMP FRAME_READY
RECORD_NEXT:
    INC INDEX
    LDAA INDEX
    CMPA #5
    BCS RECORD_SCAN
    LDAA #1
    STAA STATUS
    LDX #SFX_EMPTY
    JSR PLAY_SFX
    JMP REDRAW
PHOTO_INPUT:
    LDAA ACTION
    CMPA #5
    BEQ RETURN_NAV
    CMPA #6
    BEQ RETURN_NAV
    JMP IDLE
LOST_INPUT:
    LDAA ACTION
    CMPA #5
    BEQ REQUEST_RESET
    CMPA #6
    BEQ SHOW_TITLE
    JMP IDLE
REDRAW:
    JSR DRAW_NAV
FRAME_READY:
    JMP IDLE

REQUEST_RESET:
    JSR CONFIRM_RESET
    TSTA
    BEQ REDRAW
    JMP NEW_MISSION
REQUEST_TITLE:
    JSR CONFIRM_RESET
    TSTA
    BEQ REDRAW
    JMP SHOW_TITLE
