PLAYER_CURSOR:
    LDAA PLAYER_X
    STAA CUR_X
    LDAA PLAYER_Y
    STAA CUR_Y
    RTS
MAP_AT:
    LDX #MAP
    LDAB CUR_Y
MAP_ROW:
    TSTB
    BEQ MAP_COLUMN
    ADX #32
    DECB
    BRA MAP_ROW
MAP_COLUMN:
    LDAB CUR_X
MAP_COL:
    TSTB
    BEQ MAP_READ
    INX
    DECB
    BRA MAP_COL
MAP_READ:
    LDAA 0,X
    RTS
STEP_CURSOR:
    LDAA CUR_DIR
    CMPA #1
    BEQ STEP_N
    CMPA #2
    BEQ STEP_S
    CMPA #3
    BEQ STEP_W
    INC CUR_X
    RTS
STEP_N:
    DEC CUR_Y
    RTS
STEP_S:
    INC CUR_Y
    RTS
STEP_W:
    DEC CUR_X
    RTS
DIST_FROM_PLAYER:
    LDAA CUR_X
    SUBA PLAYER_X
    BCC DIST_X
    NEGA
DIST_X:
    STAA DISTANCE
    LDAA CUR_Y
    SUBA PLAYER_Y
    BCC DIST_Y
    NEGA
DIST_Y:
    ADDA DISTANCE
    STAA DISTANCE
    RTS
SPEND_OXYGEN:
    STAA VALUE
    LDAA OXYGEN
    SUBA VALUE
    BCC OXYGEN_STORE
    CLRA
OXYGEN_STORE:
    STAA OXYGEN
    RTS
DAMAGE_HULL:
    TST HULL
    BEQ HULL_DONE
    DEC HULL
    LDX #SFX_HIT
    JSR PLAY_SFX
    LDX #$C100 + 16
    JSR QUEUE_IMPACT
HULL_DONE:
    RTS

NAVIGATE:
    CLR STATUS
    LDAA QUIET
    INCA
    JSR SPEND_OXYGEN
    LDAA ACTION
    CMPA #7
    BEQ WORLD_STEP
    STAA CUR_DIR
    JSR PLAYER_CURSOR
    JSR STEP_CURSOR
    JSR MAP_AT
    CMPA #1
    BEQ ROCK_COLLISION
    LDAA CUR_X
    STAA PLAYER_X
    LDAA CUR_Y
    STAA PLAYER_Y
    LDX #SFX_MOVE
    JSR PLAY_SFX
    BRA WORLD_STEP
ROCK_COLLISION:
    JSR DAMAGE_HULL
WORLD_STEP:
    INC TURN
    TST SIGHT
    BEQ WORLD_NOISE
    DEC SIGHT
WORLD_NOISE:
    TST NOISE
    BEQ WORLD_GRACE
    DEC NOISE
WORLD_GRACE:
    TST GRACE
    BEQ WORLD_CURRENT
    DEC GRACE
WORLD_CURRENT:
    JSR PLAYER_CURSOR
    JSR MAP_AT
    CMPA #2
    BCS WORLD_HUNTER
    CMPA #6
    BCC WORLD_HUNTER
    SUBA #2
    TAB
    LDX #CURRENT_DIRS
CURRENT_INDEX:
    TSTB
    BEQ CURRENT_DIRECTION
    INX
    DECB
    BRA CURRENT_INDEX
CURRENT_DIRECTION:
    LDAA 0,X
    STAA CUR_DIR
    JSR STEP_CURSOR
    JSR MAP_AT
    CMPA #1
    BEQ WORLD_HUNTER
    LDAA CUR_X
    STAA PLAYER_X
    LDAA CUR_Y
    STAA PLAYER_Y
    LDAA #1
    JSR SPEND_OXYGEN
    LDX #SFX_CURRENT
    JSR PLAY_SFX
WORLD_HUNTER:
    LDAA TURN
    TST QUIET
    BEQ HUNTER_FAST
    ANDA #3
    BNE HUNTER_CONTACT
    BRA HUNTER_ACT
HUNTER_FAST:
    BITA #1
    BNE HUNTER_CONTACT
HUNTER_ACT:
    JSR MOVE_HUNTER
HUNTER_CONTACT:
    LDAA HUNTER_X
    STAA CUR_X
    LDAA HUNTER_Y
    STAA CUR_Y
    JSR DIST_FROM_PLAYER
    CMPA #1
    BHI CHECK_MISSION
    TST GRACE
    BNE CHECK_MISSION
    JSR DAMAGE_HULL
    LDAA #4
    STAA GRACE
CHECK_MISSION:
    TST HULL
    BEQ MISSION_LOST
    TST OXYGEN
    BEQ MISSION_LOST
    LDAA FLAGS
    CMPA #31
    BNE WORLD_DONE
    LDAA PLAYER_X
    CMPA #2
    BNE WORLD_DONE
    LDAA PLAYER_Y
    CMPA #2
    BNE WORLD_DONE
    LDAA #5
    STAA MODE
    JMP QUEUE_CLEAR
MISSION_LOST:
    LDAA #4
    STAA MODE
    JMP QUEUE_LOSE
WORLD_DONE:
    LDAA TURN
    ANDA #3
    BNE WORLD_WARNING_DONE
    LDAA OXYGEN
    CMPA #30
    BLS WORLD_WARNING
    LDAA HUNTER_X
    STAA CUR_X
    LDAA HUNTER_Y
    STAA CUR_Y
    JSR DIST_FROM_PLAYER
    CMPA #6
    BHI WORLD_WARNING_DONE
WORLD_WARNING:
    LDX #SFX_WARNING
    JSR PLAY_SFX
WORLD_WARNING_DONE:
    RTS

MOVE_HUNTER:
    LDAA HUNTER_X
    STAA CUR_X
    LDAA HUNTER_Y
    STAA CUR_Y
    JSR DIST_FROM_PLAYER
    CMPA #6
    BLS HUNTER_CHASE
    TST NOISE
    BNE HUNTER_CHASE
    LDAA #18
    STAA TARGET_X
    LDAA #14
    STAA TARGET_Y
    LDAA TURN
    BITA #16
    BEQ HUNTER_TARGET
    LDAA #22
    STAA TARGET_X
    LDAA #20
    STAA TARGET_Y
    BRA HUNTER_TARGET
HUNTER_CHASE:
    LDAA PLAYER_X
    STAA TARGET_X
    LDAA PLAYER_Y
    STAA TARGET_Y
HUNTER_TARGET:
    LDAA HUNTER_X
    CMPA TARGET_X
    BEQ HUNTER_TRY_Y
    BHI HUNTER_LEFT
    INC CUR_X
    BRA HUNTER_TEST_X
HUNTER_LEFT:
    DEC CUR_X
HUNTER_TEST_X:
    JSR MAP_AT
    CMPA #1
    BNE HUNTER_STORE
    LDAA HUNTER_X
    STAA CUR_X
HUNTER_TRY_Y:
    LDAA HUNTER_Y
    CMPA TARGET_Y
    BEQ HUNTER_DONE
    BHI HUNTER_UP
    INC CUR_Y
    BRA HUNTER_TEST_Y
HUNTER_UP:
    DEC CUR_Y
HUNTER_TEST_Y:
    JSR MAP_AT
    CMPA #1
    BEQ HUNTER_DONE
HUNTER_STORE:
    LDAA CUR_X
    STAA HUNTER_X
    LDAA CUR_Y
    STAA HUNTER_Y
HUNTER_DONE:
    RTS

GET_TARGET:
    CLR TARGET
    LDX #BIT_MASKS
TARGET_SCAN:
    LDAA 0,X
    BITA FLAGS
    BEQ TARGET_FOUND
    INX
    INC TARGET
    LDAA TARGET
    CMPA #5
    BCS TARGET_SCAN
    LDAA #2
    STAA TARGET_X
    STAA TARGET_Y
    BRA TARGET_BEARING
TARGET_FOUND:
    LDX #SITE_X
    LDAB TARGET
TARGET_X_INDEX:
    TSTB
    BEQ TARGET_X_READ
    INX
    DECB
    BRA TARGET_X_INDEX
TARGET_X_READ:
    LDAA 0,X
    STAA TARGET_X
    LDX #SITE_Y
    LDAB TARGET
TARGET_Y_INDEX:
    TSTB
    BEQ TARGET_Y_READ
    INX
    DECB
    BRA TARGET_Y_INDEX
TARGET_Y_READ:
    LDAA 0,X
    STAA TARGET_Y
TARGET_BEARING:
    CLR BEARING
    LDAA TARGET_X
    CMPA PLAYER_X
    BEQ BEARING_Y
    BHI BEARING_E
    LDAA #4
    BRA BEARING_X_STORE
BEARING_E:
    LDAA #8
BEARING_X_STORE:
    STAA BEARING
BEARING_Y:
    LDAA TARGET_Y
    CMPA PLAYER_Y
    BEQ BEARING_DONE
    BHI BEARING_S
    LDAA #1
    BRA BEARING_Y_STORE
BEARING_S:
    LDAA #2
BEARING_Y_STORE:
    ORAA BEARING
    STAA BEARING
BEARING_DONE:
    LDAA TARGET_X
    STAA CUR_X
    LDAA TARGET_Y
    STAA CUR_Y
    JMP DIST_FROM_PLAYER
CURRENT_DIRS:
    .byte 4,2,3,1
