GAME_START:
    CLR LEVEL
    CLR BEST_LEVEL
    CLR DEATHS
    CLR TOTAL_KILLS
SHOW_TITLE:
    CLR MODE
    LDX #TITLE_PCG
    JSR LOAD_PCG
    LDX #MUSIC_TITLE
    JSR PLAY_MUSIC
    JSR DRAW_TITLE
    JMP FRAME_READY

IDLE:
    JSR CLOCK_SERVICE
    JSR ANIMATE_IDLE
    JSR INPUT_CAPTURE
    LDAA KEY_PENDING
    BEQ IDLE
    CLR KEY_PENDING
DISPATCH:
    STAA ACTION
    LDAA MODE
    BEQ TITLE_INPUT
    CMPA #1
    BEQ PLAY_INPUT
    CMPA #2
    BEQ MENU_INPUT
    CMPA #3
    BEQ DEAD_INPUT
    CMPA #4
    BEQ CLEAR_INPUT
    CMPA #5
    BEQ WIN_INPUT
    JMP SHOW_TITLE
TITLE_INPUT:
    LDAA ACTION
    CMPA #5
    BEQ START_LEVEL
    CMPA #6
    BEQ SHOW_HELP
    CMPA #3
    BEQ TITLE_PREVIOUS
    CMPA #4
    BNE IDLE
    LDAA LEVEL
    CMPA BEST_LEVEL
    BCC IDLE
    INC LEVEL
    JSR DRAW_TITLE
    JMP FRAME_READY
TITLE_PREVIOUS:
    TST LEVEL
    BEQ IDLE
    DEC LEVEL
    JSR DRAW_TITLE
    JMP FRAME_READY
SHOW_HELP:
    LDAA #6
    STAA MODE
    JSR DRAW_HELP
    JMP FRAME_READY
START_LEVEL:
    JSR SOUND_STOP
    LDX #GAME_PCG
    JSR LOAD_PCG
    JSR LOAD_LEVEL
    JMP REDRAW_GAME
PLAY_INPUT:
    LDAA ACTION
    CMPA #5
    BEQ OPEN_MENU
    CMPA #6
    BEQ OPEN_MENU
    JSR TAKE_ACTION
    JMP REDRAW_GAME
OPEN_MENU:
    LDAA #2
    STAA MODE
    CLR MENU
    LDX #SFX_MENU
    JSR PLAY_SFX
    JMP REDRAW_GAME
MENU_INPUT:
    LDAA ACTION
    CMPA #6
    BEQ CLOSE_MENU
    CMPA #1
    BEQ MENU_UP
    CMPA #2
    BEQ MENU_DOWN
    CMPA #3
    BEQ AIM_LEFT
    CMPA #4
    BEQ AIM_RIGHT
    CMPA #5
    BNE IDLE
    LDAA MENU
    BEQ MENU_FIRE
    CMPA #1
    BEQ MENU_WAIT
    CMPA #2
    BEQ START_LEVEL
    CMPA #3
    BEQ SHOW_TITLE
    JMP CLOSE_MENU
MENU_UP:
    DEC MENU
    BPL REDRAW_GAME
    LDAA #4
    STAA MENU
    JMP REDRAW_GAME
MENU_DOWN:
    INC MENU
    LDAA MENU
    CMPA #5
    BCS REDRAW_GAME
    CLR MENU
    JMP REDRAW_GAME
AIM_LEFT:
    DEC FACING
    BNE REDRAW_GAME
    LDAA #4
    STAA FACING
    JMP REDRAW_GAME
AIM_RIGHT:
    INC FACING
    LDAA FACING
    CMPA #5
    BCS REDRAW_GAME
    LDAA #1
    STAA FACING
    JMP REDRAW_GAME
MENU_FIRE:
    LDAA #8
    STAA ACTION
    BRA MENU_ACT
MENU_WAIT:
    LDAA #7
    STAA ACTION
MENU_ACT:
    LDAA #1
    STAA MODE
    JSR TAKE_ACTION
    JMP REDRAW_GAME
CLOSE_MENU:
    LDAA #1
    STAA MODE
    JMP REDRAW_GAME
DEAD_INPUT:
    LDAA ACTION
    CMPA #5
    BEQ START_LEVEL
    CMPA #6
    BEQ SHOW_TITLE
    JMP IDLE
CLEAR_INPUT:
    LDAA ACTION
    CMPA #5
    BNE IDLE
    INC LEVEL
    LDAA LEVEL
    CMPA #20
    BEQ GAME_WON
    STAA BEST_LEVEL
    JMP START_LEVEL
GAME_WON:
    LDAA #19
    STAA LEVEL
    LDAA #5
    STAA MODE
    JMP REDRAW_GAME
WIN_INPUT:
    LDAA ACTION
    CMPA #5
    BEQ SHOW_TITLE
    CMPA #6
    BEQ SHOW_TITLE
    JMP IDLE

REDRAW_GAME:
    JSR DRAW_GAME
FRAME_READY:
    JMP IDLE

LOAD_LEVEL:
    LDX #MAP
    CLRA
LEVEL_ZERO:
    STAA 0,X
    INX
    CPX #BULLETS + 48
    BNE LEVEL_ZERO
    LDAA #1
    STAA MODE
    LDAA #4
    STAA FACING
    CLR TURNS
    LDAA #2
    STAA PHASE
    LDX #LEVEL_TABLE
    LDAB LEVEL
    ASLB
LEVEL_TABLE_INDEX:
    TSTB
    BEQ LEVEL_TABLE_READ
    INX
    DECB
    BRA LEVEL_TABLE_INDEX
LEVEL_TABLE_READ:
    LDX 0,X
    LDAA 0,X
    STAA PLAYER_X
    LDAA 1,X
    STAA PLAYER_Y
    LDAA 2,X
    STAA EXIT_X
    LDAA 3,X
    STAA EXIT_Y
    LDAA 4,X
    STAA ENEMY_COUNT
    STAA ALIVE
    LDAA 5,X
    STAA AMMO
    LDAA 6,X
    STAA PAR
    LDAB #7
LEVEL_SKIP_HEADER:
    INX
    DECB
    BNE LEVEL_SKIP_HEADER
    STX LEVEL_PTR
    LDX #ENEMIES
    STX SLOT_PTR
    LDAA ENEMY_COUNT
    STAA INDEX
LEVEL_ENEMY:
    LDX LEVEL_PTR
    LDAA 0,X
    LDAB 1,X
    LDX SLOT_PTR
    STAA 0,X
    STAB 1,X
    LDX LEVEL_PTR
    LDAA 2,X
    INX
    INX
    INX
    STX LEVEL_PTR
    LDX SLOT_PTR
    STAA 2,X
    LDAA #1
    STAA 3,X
    INX
    INX
    INX
    INX
    STX SLOT_PTR
    DEC INDEX
    BNE LEVEL_ENEMY
    LDX #MAP
    STX DST
LEVEL_RUN:
    LDX LEVEL_PTR
    LDAB 0,X
    LDAA 1,X
    INX
    INX
    STX LEVEL_PTR
    LDX DST
LEVEL_RUN_BYTE:
    STAA 0,X
    INX
    DECB
    BNE LEVEL_RUN_BYTE
    STX DST
    CPX #MAP + 120
    BNE LEVEL_RUN
    RTS
