; CUR_X/CUR_Y -> X map cell, A tile. Border walls keep moves in bounds.
MAP_AT:
    LDX #MAP
    LDAB CUR_Y
MAP_ROW:
    TSTB
    BEQ MAP_COLUMN
    ADX #12
    DECB
    BRA MAP_ROW
MAP_COLUMN:
    LDAB CUR_X
MAP_COL_LOOP:
    TSTB
    BEQ MAP_READ
    INX
    DECB
    BRA MAP_COL_LOOP
MAP_READ:
    LDAA 0,X
    RTS

STEP_CURSOR:
    LDAA CUR_DIR
    CMPA #1
    BEQ STEP_NORTH
    CMPA #2
    BEQ STEP_SOUTH
    CMPA #3
    BEQ STEP_WEST
    INC CUR_X
    RTS
STEP_NORTH:
    DEC CUR_Y
    RTS
STEP_SOUTH:
    INC CUR_Y
    RTS
STEP_WEST:
    DEC CUR_X
    RTS

PLAYER_CURSOR:
    LDAA PLAYER_X
    STAA CUR_X
    LDAA PLAYER_Y
    STAA CUR_Y
    RTS

; Kill the first living guard at the cursor; A=1 on hit, otherwise 0.
HIT_GUARD:
    LDX #ENEMIES
GUARD_SCAN:
    TST 3,X
    BEQ GUARD_NEXT
    LDAA CUR_X
    CMPA 0,X
    BNE GUARD_NEXT
    LDAA CUR_Y
    CMPA 1,X
    BNE GUARD_NEXT
    CLR 3,X
    DEC ALIVE
    LDAA TOTAL_KILLS
    CMPA #255
    BEQ GUARD_KILL_SOUND
    INC TOTAL_KILLS
GUARD_KILL_SOUND:
    LDX #SFX_KILL
    JSR PLAY_SFX
    LDAA #1
    RTS
GUARD_NEXT:
    ADX #4
    CPX #ENEMIES + 24
    BNE GUARD_SCAN
    CLRA
    RTS

; Set death only once even when several bolts hit together.
HIT_PLAYER:
    LDAA CUR_X
    CMPA PLAYER_X
    BNE HIT_PLAYER_MISS
    LDAA CUR_Y
    CMPA PLAYER_Y
    BNE HIT_PLAYER_MISS
    LDAA MODE
    CMPA #3
    BEQ HIT_PLAYER_YES
    LDAA #3
    STAA MODE
    LDAA DEATHS
    CMPA #255
    BEQ DEATH_SOUND
    INC DEATHS
DEATH_SOUND:
    LDX #SFX_DEATH
    JSR PLAY_SFX
HIT_PLAYER_YES:
    LDAA #1
    RTS
HIT_PLAYER_MISS:
    CLRA
    RTS

TAKE_ACTION:
    LDAA ACTION
    CMPA #7
    BEQ ADVANCE_WORLD
    CMPA #8
    BEQ PLAYER_FIRE
    CMPA #1
    BCS ACTION_DONE
    CMPA #5
    BCC ACTION_DONE
    STAA FACING
    STAA CUR_DIR
    JSR PLAYER_CURSOR
    JSR STEP_CURSOR
    JSR MAP_AT
    CMPA #1
    BEQ ACTION_DONE
    LDAA CUR_X
    STAA PLAYER_X
    LDAA CUR_Y
    STAA PLAYER_Y
    JSR HIT_GUARD
    LDX #SFX_MOVE
    JSR PLAY_SFX
    ; Entering an occupied bolt cell is lethal before that bolt advances.
    LDX #BULLETS
ENTER_BOLT:
    TST 2,X
    BEQ ENTER_BOLT_NEXT
    LDAA 0,X
    CMPA PLAYER_X
    BNE ENTER_BOLT_NEXT
    LDAA 1,X
    CMPA PLAYER_Y
    BNE ENTER_BOLT_NEXT
    STX SCAN_PTR
    JSR HIT_PLAYER
    LDX SCAN_PTR
ENTER_BOLT_NEXT:
    ADX #3
    CPX #BULLETS + 48
    BNE ENTER_BOLT
    BRA ADVANCE_WORLD
PLAYER_FIRE:
    TST AMMO
    BNE FIRE_READY
    LDX #SFX_EMPTY
    JMP PLAY_SFX
FIRE_READY:
    DEC AMMO
    JSR PLAYER_CURSOR
    LDAA FACING
    STAA CUR_DIR
    LDAA #4
    STAA RAY_LEFT
    LDX #SFX_SHOT
    JSR PLAY_SFX
FIRE_RAY:
    JSR STEP_CURSOR
    JSR MAP_AT
    CMPA #1
    BEQ ADVANCE_WORLD
    JSR HIT_GUARD
    TSTA
    BNE ADVANCE_WORLD
    DEC RAY_LEFT
    BNE FIRE_RAY
ADVANCE_WORLD:
    LDAA TURNS
    CMPA #255
    BEQ ADVANCE_BOLTS
    INC TURNS
ADVANCE_BOLTS:
    LDX #BULLETS
    STX SLOT_PTR
BOLT_LOOP:
    LDX SLOT_PTR
    LDAA 2,X
    BEQ BOLT_NEXT
    STAA CUR_DIR
    LDAA 0,X
    STAA CUR_X
    LDAA 1,X
    STAA CUR_Y
    JSR STEP_CURSOR
    JSR MAP_AT
    CMPA #1
    BEQ BOLT_REMOVE
    JSR HIT_PLAYER
    TSTA
    BNE BOLT_REMOVE
    JSR HIT_GUARD
    TSTA
    BNE BOLT_REMOVE
    LDX SLOT_PTR
    LDAA CUR_X
    STAA 0,X
    LDAA CUR_Y
    STAA 1,X
    BRA BOLT_NEXT
BOLT_REMOVE:
    LDX SLOT_PTR
    CLR 2,X
BOLT_NEXT:
    LDX SLOT_PTR
    ADX #3
    STX SLOT_PTR
    CPX #BULLETS + 48
    BNE BOLT_LOOP
    INC PHASE
    LDAA PHASE
    CMPA #3
    BCS CHECK_CLEAR
    CLR PHASE
    LDX #ENEMIES
    STX RAY_PTR
GUARD_FIRE_LOOP:
    LDX RAY_PTR
    TST 3,X
    BEQ GUARD_FIRE_NEXT
    LDAA 0,X
    STAA CUR_X
    LDAA 1,X
    STAA CUR_Y
    LDAA 2,X
    STAA CUR_DIR
    JSR STEP_CURSOR
    JSR MAP_AT
    CMPA #1
    BEQ GUARD_FIRE_NEXT
    JSR HIT_PLAYER
    TSTA
    BNE GUARD_FIRE_NEXT
    JSR HIT_GUARD
    TSTA
    BNE GUARD_FIRE_NEXT
    LDX #BULLETS
BOLT_ALLOCATE:
    TST 2,X
    BEQ BOLT_SPAWN
    ADX #3
    CPX #BULLETS + 48
    BNE BOLT_ALLOCATE
    BRA GUARD_FIRE_NEXT
BOLT_SPAWN:
    LDAA CUR_X
    STAA 0,X
    LDAA CUR_Y
    STAA 1,X
    LDAA CUR_DIR
    STAA 2,X
GUARD_FIRE_NEXT:
    LDX RAY_PTR
    ADX #4
    STX RAY_PTR
    CPX #ENEMIES + 24
    BNE GUARD_FIRE_LOOP
CHECK_CLEAR:
    LDAA MODE
    CMPA #1
    BNE ACTION_DONE
    TST ALIVE
    BNE ACTION_DONE
    LDAA PLAYER_X
    CMPA EXIT_X
    BNE ACTION_DONE
    LDAA PLAYER_Y
    CMPA EXIT_Y
    BNE ACTION_DONE
    LDAA #4
    STAA MODE
    JSR QUEUE_CLEAR
ACTION_DONE:
    RTS
