; Generated JR-100 sound assets
SOUND_TICK_HZ: .equ 60

.data
SOUND_BGM_ODE_TO_JOY_OPENING:
        .word SOUND_BGM_ODE_TO_JOY_OPENING_EVENTS
        .byte 16, $00
SOUND_BGM_ODE_TO_JOY_OPENING_EVENTS:
        .byte $11, $06
        .byte $11, $06
        .byte $12, $06
        .byte $14, $06
        .byte $14, $06
        .byte $12, $06
        .byte $11, $06
        .byte $0F, $06
        .byte $0D, $06
        .byte $0D, $06
        .byte $0F, $06
        .byte $11, $06
        .byte $11, $06
        .byte $0F, $06
        .byte $0F, $06
        .byte $00, $06
SOUND_BGM_AH_VOUS_DIRAIJE_OPENING:
        .word SOUND_BGM_AH_VOUS_DIRAIJE_OPENING_EVENTS
        .byte 16, $00
SOUND_BGM_AH_VOUS_DIRAIJE_OPENING_EVENTS:
        .byte $0D, $06
        .byte $0D, $06
        .byte $14, $06
        .byte $14, $06
        .byte $16, $06
        .byte $16, $06
        .byte $14, $06
        .byte $00, $06
        .byte $12, $06
        .byte $12, $06
        .byte $11, $06
        .byte $11, $06
        .byte $0F, $06
        .byte $0F, $06
        .byte $0D, $06
        .byte $00, $06
SOUND_SFX_BLIP:
        .byte 4
        .byte $25, $01
        .byte $29, $01
        .byte $2D, $01
        .byte $00, $01
