NEXT_RANDOM:
    LDAA RNG
    ASLA
    BCC RANDOM_STORE
    EORA #$1D
RANDOM_STORE:
    STAA RNG
    RTS
RANDOM_CARD:
    JSR NEXT_RANDOM
RANDOM_CARD_MOD:
    CMPA #24
    BCS RANDOM_CARD_DONE
    SUBA #24
    BRA RANDOM_CARD_MOD
RANDOM_CARD_DONE:
    RTS

CARD_ADDRESS:
    LDX #CARD_STATS
    LDAB CARD_ID
CARD_ADDRESS_LOOP:
    TSTB
    BEQ CARD_ADDRESS_DONE
    ADX #6
    DECB
    BRA CARD_ADDRESS_LOOP
CARD_ADDRESS_DONE:
    STX CARD_PTR
    RTS

; Draw uniformly by slot (small modulo bias), remove by swapping the tail.
DRAW_ONE:
    TST DRAW_COUNT
    BNE DRAW_AVAILABLE
    TST DISCARD_COUNT
    BEQ DRAW_NONE
    LDAA DISCARD_COUNT
    STAA DRAW_COUNT
    STAA COUNT + 1
    CLR COUNT
    CLR DISCARD_COUNT
    LDX #DISCARD_PILE
    STX SRC
    LDX #DRAW_PILE
    STX DST
    JSR COPY
DRAW_AVAILABLE:
    JSR NEXT_RANDOM
DRAW_MOD:
    CMPA DRAW_COUNT
    BCS DRAW_INDEX_READY
    SUBA DRAW_COUNT
    BRA DRAW_MOD
DRAW_INDEX_READY:
    TAB
    LDX #DRAW_PILE
DRAW_INDEX:
    TSTB
    BEQ DRAW_READ
    INX
    DECB
    BRA DRAW_INDEX
DRAW_READ:
    STX DRAW_PTR
    LDAA 0,X
    STAA CARD_VALUE
    DEC DRAW_COUNT
    LDAB DRAW_COUNT
    LDX #DRAW_PILE
DRAW_TAIL:
    TSTB
    BEQ DRAW_SWAP
    INX
    DECB
    BRA DRAW_TAIL
DRAW_SWAP:
    LDAA 0,X
    LDX DRAW_PTR
    STAA 0,X
    LDAA CARD_VALUE
    RTS
DRAW_NONE:
    LDAA #255
    RTS
DRAW_HAND:
    CLR HAND_SLOT
DRAW_HAND_SLOT:
    LDX #HAND
    LDAB HAND_SLOT
DRAW_HAND_INDEX:
    TSTB
    BEQ DRAW_HAND_EMPTY
    INX
    DECB
    BRA DRAW_HAND_INDEX
DRAW_HAND_EMPTY:
    LDAA 0,X
    CMPA #255
    BNE DRAW_HAND_NEXT
    JSR DRAW_ONE
    STAA CARD_VALUE
    LDX #HAND
    LDAB HAND_SLOT
DRAW_HAND_PUT_INDEX:
    TSTB
    BEQ DRAW_HAND_PUT
    INX
    DECB
    BRA DRAW_HAND_PUT_INDEX
DRAW_HAND_PUT:
    LDAA CARD_VALUE
    STAA 0,X
    CMPA #255
    BEQ DRAW_HAND_DONE
    DEC DRAW_MORE
    BEQ DRAW_HAND_DONE
DRAW_HAND_NEXT:
    INC HAND_SLOT
    LDAA HAND_SLOT
    CMPA #4
    BCS DRAW_HAND_SLOT
DRAW_HAND_DONE:
    RTS

PLAYER_TURN:
    TST RETAIN
    BNE PLAYER_RETAINS
    CLR SHIELD
PLAYER_RETAINS:
    CLR RETAIN
    CLR THORNS
    LDAA #3
    STAA ENERGY
    LDAA #4
    STAA DRAW_MORE
    JSR DRAW_HAND
    LDAA TURN
    CMPA #255
    BEQ PLAYER_TURN_DONE
    INC TURN
PLAYER_TURN_DONE:
    RTS

DISCARD_CARD:
    LDX #DISCARD_PILE
    LDAB DISCARD_COUNT
DISCARD_INDEX:
    TSTB
    BEQ DISCARD_PUT
    INX
    DECB
    BRA DISCARD_INDEX
DISCARD_PUT:
    STAA 0,X
    INC DISCARD_COUNT
    RTS

PLAY_CARD:
    LDX #HAND
    LDAB SELECTED
PLAY_CARD_INDEX:
    TSTB
    BEQ PLAY_CARD_READ
    INX
    DECB
    BRA PLAY_CARD_INDEX
PLAY_CARD_READ:
    LDAA 0,X
    CMPA #255
    BEQ CANNOT_PLAY
    STAA CARD_ID
    JSR CARD_ADDRESS
    LDAA ENERGY
    CMPA 0,X
    BCS CANNOT_PLAY
    SUBA 0,X
    STAA ENERGY
    LDAA TOTAL_CARDS
    CMPA #255
    BEQ REMOVE_PLAYED
    INC TOTAL_CARDS
REMOVE_PLAYED:
    LDX #HAND
    LDAB SELECTED
REMOVE_HAND_INDEX:
    TSTB
    BEQ REMOVE_HAND
    INX
    DECB
    BRA REMOVE_HAND_INDEX
REMOVE_HAND:
    LDAA #255
    STAA 0,X
    JMP CARD_ATTACK
CARD_ATTACK:
    LDX CARD_PTR
    LDAA 1,X
    BEQ CARD_BLOCK
    ADDA STRENGTH
    STAA DAMAGE
    LDAA 3,X
    CMPA #12
    BNE CARD_ECHO
    LDAA ENEMY_HP
    CMPA #12
    BHI CARD_ECHO
    LDAA DAMAGE
    ADDA #12
    STAA DAMAGE
CARD_ECHO:
    TST ECHO
    BEQ CARD_VULNERABLE
    ASL DAMAGE
    CLR ECHO
CARD_VULNERABLE:
    TST VULNERABLE
    BEQ CARD_HIT
    LDAA DAMAGE
    LSRA
    ADDA DAMAGE
    STAA DAMAGE
CARD_HIT:
    JSR HURT_ENEMY
    LDX #SFX_SHOT
    JSR PLAY_SFX
CARD_BLOCK:
    LDX CARD_PTR
    LDAA 2,X
    BEQ CARD_SPECIAL
    ADDA SHIELD
    CMPA #99
    BCS STORE_SHIELD
    LDAA #99
STORE_SHIELD:
    STAA SHIELD
    LDX #SFX_SHIELD
    JSR PLAY_SFX
CARD_SPECIAL:
    LDX CARD_PTR
    LDAA 4,X
    STAA CARD_VALUE
    LDAA 3,X
    BEQ CARD_DONE
    CMPA #1
    BEQ CARD_HEAL
    CMPA #2
    BEQ CARD_ENERGY
    CMPA #3
    BEQ CARD_POISON
    CMPA #4
    BEQ CARD_HASTE
    CMPA #5
    BEQ CARD_THORN
    CMPA #6
    BEQ CARD_VULN
    CMPA #7
    BEQ CARD_DOUBLE
    CMPA #8
    BEQ CARD_RETAIN
    CMPA #9
    BEQ CARD_STRENGTH
    CMPA #10
    BEQ CARD_WEAK
    CMPA #11
    BEQ CARD_DRAW
    BRA CARD_DONE
CARD_HEAL:
    LDAA CARD_VALUE
    JSR HEAL_PLAYER
    LDX #SFX_HEAL
    JSR PLAY_SFX
    BRA CARD_DONE
CARD_ENERGY:
    LDAA CARD_VALUE
    ADDA ENERGY
    CMPA #9
    BCS STORE_ENERGY
    LDAA #9
STORE_ENERGY:
    STAA ENERGY
    BRA CARD_DONE
CARD_POISON:
    LDAA CARD_VALUE
    ADDA POISON
    CMPA #99
    BCS STORE_POISON
    LDAA #99
STORE_POISON:
    STAA POISON
    LDX #SFX_POISON
    JSR PLAY_SFX
    BRA CARD_DONE
CARD_HASTE:
    INC ENERGY
    LDAA #1
    STAA DRAW_MORE
    JSR DRAW_HAND
    BRA CARD_DONE
CARD_THORN:
    LDAA CARD_VALUE
    ADDA THORNS
    STAA THORNS
    BRA CARD_DONE
CARD_VULN:
    LDAA #2
    STAA VULNERABLE
    BRA CARD_DONE
CARD_DOUBLE:
    LDAA #1
    STAA ECHO
    BRA CARD_DONE
CARD_RETAIN:
    LDAA #1
    STAA RETAIN
    BRA CARD_DONE
CARD_STRENGTH:
    LDAA STRENGTH
    ADDA CARD_VALUE
    CMPA #20
    BCS STORE_STRENGTH
    LDAA #20
STORE_STRENGTH:
    STAA STRENGTH
    BRA CARD_DONE
CARD_WEAK:
    LDAA #2
    STAA WEAK
    BRA CARD_DONE
CARD_DRAW:
    LDAA CARD_VALUE
    STAA DRAW_MORE
    JSR DRAW_HAND
CARD_DONE:
    LDX CARD_PTR
    TST 5,X
    BNE EXHAUST_CARD
    LDAA CARD_ID
    JSR DISCARD_CARD
    BRA CARD_RESOLVED
EXHAUST_CARD:
    LDX #EXHAUST_PILE
    LDAB EXHAUST_COUNT
EXHAUST_INDEX:
    TSTB
    BEQ EXHAUST_PUT
    INX
    DECB
    BRA EXHAUST_INDEX
EXHAUST_PUT:
    LDAA CARD_ID
    STAA 0,X
    INC EXHAUST_COUNT
CARD_RESOLVED:
    JMP CHECK_VICTORY
CANNOT_PLAY:
    LDX #SFX_EMPTY
    JMP PLAY_SFX

HEAL_PLAYER:
    ADDA HP
    CMPA #60
    BCS STORE_HP
    LDAA #60
STORE_HP:
    STAA HP
    RTS
HURT_ENEMY:
    LDAA DAMAGE
    CMPA ENEMY_SHIELD
    BHI ENEMY_PENETRATE
    LDAA ENEMY_SHIELD
    SUBA DAMAGE
    STAA ENEMY_SHIELD
    RTS
ENEMY_PENETRATE:
    SUBA ENEMY_SHIELD
    STAA DAMAGE
    CLR ENEMY_SHIELD
    LDAA ENEMY_HP
    SUBA DAMAGE
    BCC ENEMY_HP_STORE
    CLRA
ENEMY_HP_STORE:
    STAA ENEMY_HP
    RTS

ENEMY_TURN:
    CLR HAND_SLOT
DISCARD_HAND:
    LDX #HAND
    LDAB HAND_SLOT
DISCARD_HAND_INDEX:
    TSTB
    BEQ DISCARD_HAND_READ
    INX
    DECB
    BRA DISCARD_HAND_INDEX
DISCARD_HAND_READ:
    LDAA 0,X
    CMPA #255
    BEQ DISCARD_HAND_NEXT
    LDAB #255
    STAB 0,X
    JSR DISCARD_CARD
DISCARD_HAND_NEXT:
    INC HAND_SLOT
    LDAA HAND_SLOT
    CMPA #4
    BCS DISCARD_HAND
    CLR ENEMY_SHIELD
    TST POISON
    BEQ ENEMY_INTENT
    LDAA ENEMY_HP
    SUBA POISON
    BCC POISON_DAMAGE
    CLRA
POISON_DAMAGE:
    STAA ENEMY_HP
    DEC POISON
    JSR CHECK_VICTORY
    LDAA MODE
    CMPA #1
    BNE ENEMY_TURN_DONE
ENEMY_INTENT:
    LDAA INTENT
    CMPA #1
    BEQ ENEMY_BLOCK
    LDAA ENEMY_ATTACK
    TST INTENT
    BEQ ENEMY_WEAKEN
    ADDA #2
ENEMY_WEAKEN:
    TST WEAK
    BEQ ENEMY_DAMAGE
    SUBA #3
    BCC ENEMY_DAMAGE
    CLRA
ENEMY_DAMAGE:
    STAA DAMAGE
    CMPA SHIELD
    BHI PLAYER_PENETRATE
    LDAA SHIELD
    SUBA DAMAGE
    STAA SHIELD
    BRA APPLY_THORNS
PLAYER_PENETRATE:
    SUBA SHIELD
    STAA DAMAGE
    CLR SHIELD
    LDAA HP
    SUBA DAMAGE
    BCC PLAYER_HP_STORE
    CLRA
PLAYER_HP_STORE:
    STAA HP
    LDX #SFX_HIT
    JSR PLAY_SFX
APPLY_THORNS:
    LDAA THORNS
    STAA DAMAGE
    JSR HURT_ENEMY
    BRA ENEMY_TURN_FINISH
ENEMY_BLOCK:
    LDAA ENEMY_GUARD
    STAA ENEMY_SHIELD
ENEMY_TURN_FINISH:
    TST WEAK
    BEQ DEC_VULN
    DEC WEAK
DEC_VULN:
    TST VULNERABLE
    BEQ NEXT_INTENT
    DEC VULNERABLE
NEXT_INTENT:
    INC INTENT
    LDAA INTENT
    CMPA #3
    BCS KEEP_INTENT
    CLR INTENT
KEEP_INTENT:
    JSR CHECK_VICTORY
    LDAA MODE
    CMPA #1
    BNE ENEMY_TURN_DONE
    JSR PLAYER_TURN
ENEMY_TURN_DONE:
    RTS
