TEXT_TABLE:
    STX TABLE_PTR
TEXT_TABLE_NEXT:
    LDX TABLE_PTR
    LDAA 0,X
    ORAA 1,X
    BEQ TEXT_TABLE_DONE
    LDX 0,X
    STX TEXT_OUT
    LDX TABLE_PTR
    LDX 2,X
    STX TEXT_PTR
    JSR TEXT
    LDX TABLE_PTR
    ADX #4
    STX TABLE_PTR
    BRA TEXT_TABLE_NEXT
TEXT_TABLE_DONE:
    RTS
DRAW_TITLE:
    LDX #TITLE_SCREEN
    STX SRC
    LDX #FRAMEBUFFER
    STX DST
    LDX #768
    STX COUNT
    JSR COPY
    LDX #TITLE_TEXT
    JSR TEXT_TABLE
    JMP PRESENT
DRAW_HELP:
    JSR CLEAR_SCREEN
    LDX #HELP_TEXT
    JSR TEXT_TABLE
    JMP PRESENT
LOAD_ENEMY_PCG:
    LDX #GAME_PCG
    JMP LOAD_PCG

DRAW_BATTLE:
    JSR CLEAR_SCREEN
    LDAA MODE
    CMPA #2
    BEQ DRAW_REWARD
    CMPA #3
    BEQ DRAW_DEATH
    CMPA #4
    BEQ DRAW_WIN
    LDX #HUD_TEXT
    JSR TEXT_TABLE
    LDAA HP
    LDX #FRAMEBUFFER + 3
    JSR NUMBER
    LDAA SHIELD
    LDX #FRAMEBUFFER + 13
    JSR NUMBER
    LDAA ENERGY
    LDX #FRAMEBUFFER + 24
    JSR NUMBER
    LDAA BATTLE
    INCA
    LDX #FRAMEBUFFER + 32 + 2
    JSR NUMBER
    LDAA DRAW_COUNT
    LDX #FRAMEBUFFER + 32 + 12
    JSR NUMBER
    LDAA DISCARD_COUNT
    LDX #FRAMEBUFFER + 32 + 22
    JSR NUMBER
    JSR CLOCK_SERVICE
    LDAA EXHAUST_COUNT
    LDX #FRAMEBUFFER + 32 + 28
    JSR NUMBER
    LDAA ENEMY_HP
    LDX #FRAMEBUFFER + 32 * 4 + 4
    JSR NUMBER
    LDAA ENEMY_SHIELD
    LDX #FRAMEBUFFER + 32 * 6 + 4
    JSR NUMBER
    LDAA POISON
    LDX #FRAMEBUFFER + 32 * 8 + 4
    JSR NUMBER
    LDAA WEAK
    LDX #FRAMEBUFFER + 32 * 10 + 4
    JSR NUMBER
    LDAA STRENGTH
    LDX #FRAMEBUFFER + 32 * 4 + 25
    JSR NUMBER
    LDAA VULNERABLE
    LDX #FRAMEBUFFER + 32 * 6 + 25
    JSR NUMBER
    LDAA ECHO
    LDX #FRAMEBUFFER + 32 * 8 + 25
    JSR NUMBER
    LDAA THORNS
    LDX #FRAMEBUFFER + 32 * 10 + 25
    JSR NUMBER
    LDAA ENEMY_ID
    LDX #ENEMY_NAMES
    JSR POINTER_INDEX
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 32 * 2 + 9
    STX TEXT_OUT
    JSR TEXT
    LDAA ENEMY_ID
    LDX #MONSTER_TABLE
    JSR POINTER_INDEX
    STX SRC
    LDX #FRAMEBUFFER + 32 * 3 + 12
    STX DST
    LDAA #8
    STAA DRAW_Y
MONSTER_ROW:
    LDAB #8
MONSTER_CELL:
    LDX SRC
    LDAA 0,X
    INX
    STX SRC
    LDX DST
    STAA 0,X
    INX
    STX DST
    DECB
    BNE MONSTER_CELL
    ADX #24
    STX DST
    JSR CLOCK_SERVICE
    DEC DRAW_Y
    BNE MONSTER_ROW
    LDX #HIT_TEXT
    LDAA ENEMY_ATTACK
    STAA CARD_VALUE
    LDAA INTENT
    CMPA #1
    BEQ DRAW_GUARD_INTENT
    TSTA
    BEQ DRAW_WEAK_INTENT
    INC CARD_VALUE
    INC CARD_VALUE
DRAW_WEAK_INTENT:
    TST WEAK
    BEQ DRAW_INTENT
    LDAA CARD_VALUE
    SUBA #3
    BCC DRAW_ATTACK_VALUE
    CLRA
DRAW_ATTACK_VALUE:
    STAA CARD_VALUE
    BRA DRAW_INTENT
DRAW_GUARD_INTENT:
    LDX #GUARD_TEXT
    LDAA ENEMY_GUARD
    STAA CARD_VALUE
DRAW_INTENT:
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 32 * 11 + 7
    STX TEXT_OUT
    JSR TEXT
    LDAA CARD_VALUE
    LDX #FRAMEBUFFER + 32 * 11 + 20
    JSR NUMBER
    CLR INDEX
DRAW_HAND_CARDS:
    LDX #HAND
    LDAB INDEX
HAND_CARD_INDEX:
    TSTB
    BEQ HAND_CARD_READ
    INX
    DECB
    BRA HAND_CARD_INDEX
HAND_CARD_READ:
    LDAA 0,X
    STAA CARD_ID
    LDX #FRAMEBUFFER + 32 * 13
    LDAB INDEX
CARD_POSITION:
    TSTB
    BEQ CARD_POSITION_DONE
    ADX #8
    DECB
    BRA CARD_POSITION
CARD_POSITION_DONE:
    STX DRAW_PTR
    JSR DRAW_CARD
    JSR CLOCK_SERVICE
    INC INDEX
    LDAA INDEX
    CMPA #4
    BCS DRAW_HAND_CARDS
    LDAA SELECTED
    CMPA #4
    BEQ DRAW_END_TURN
    LDX #FRAMEBUFFER + 32 * 12 + 3
    LDAB SELECTED
DRAW_ARROW_INDEX:
    TSTB
    BEQ DRAW_ARROW
    ADX #8
    DECB
    BRA DRAW_ARROW_INDEX
DRAW_ARROW:
    LDAA #$99
    STAA 0,X
    LDX #HAND
    LDAB SELECTED
DESCRIPTION_INDEX:
    TSTB
    BEQ DESCRIPTION_READ
    INX
    DECB
    BRA DESCRIPTION_INDEX
DESCRIPTION_READ:
    LDAA 0,X
    CMPA #255
    BEQ DESCRIPTION_EMPTY
    LDX #CARD_DESCRIPTIONS
    JSR POINTER_INDEX
    BRA DESCRIPTION_SHOW
DESCRIPTION_EMPTY:
    LDX #EMPTY_TEXT
    BRA DESCRIPTION_SHOW
DRAW_END_TURN:
    LDAA #30
    STAA FRAMEBUFFER + 32 * 19 + 9
    LDX #END_TEXT
DESCRIPTION_SHOW:
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 32 * 21
    STX TEXT_OUT
    JSR TEXT
    JMP PRESENT

; A indexes a word-pointer table at X.
POINTER_INDEX:
    ASLA
    TAB
POINTER_LOOP:
    TSTB
    BEQ POINTER_READ
    INX
    DECB
    BRA POINTER_LOOP
POINTER_READ:
    LDX 0,X
    RTS

; CARD_ID and DRAW_PTR choose a six-row, eight-column card panel.
DRAW_CARD:
    LDX DRAW_PTR
    LDAB #8
    LDAA #$96
CARD_TOP_BOTTOM:
    STAA 0,X
    STAA 160,X
    INX
    DECB
    BNE CARD_TOP_BOTTOM
    LDX DRAW_PTR
    ADX #32
    LDAB #4
    LDAA #$97
CARD_SIDES:
    STAA 0,X
    STAA 7,X
    ADX #32
    DECB
    BNE CARD_SIDES
    LDAA CARD_ID
    CMPA #255
    BEQ EMPTY_CARD_DONE
    LDX #CARD_NAMES
    JSR POINTER_INDEX
    STX TEXT_PTR
    LDX DRAW_PTR
    ADX #33
    STX TEXT_OUT
    JSR TEXT
    JSR CARD_ADDRESS
    LDAA 0,X
    ADDA #16
    LDX DRAW_PTR
    STAA 65,X
    LDX #COST_TEXT
    STX TEXT_PTR
    LDX DRAW_PTR
    ADX #67
    STX TEXT_OUT
    JSR TEXT
    LDX CARD_PTR
    LDAA 1,X
    BNE CARD_ATTACK_STAT
    LDAA 2,X
    BNE CARD_BLOCK_STAT
    LDAA 4,X
    STAA CARD_VALUE
    LDAA #$95
    STAA POSE
    LDX #MAGIC_TEXT
    BRA DRAW_CARD_STAT
CARD_ATTACK_STAT:
    STAA CARD_VALUE
    LDAA #$90
    STAA POSE
    LDX #ATTACK_TEXT
    BRA DRAW_CARD_STAT
CARD_BLOCK_STAT:
    STAA CARD_VALUE
    LDAA #$91
    STAA POSE
    LDX #BLOCK_TEXT
DRAW_CARD_STAT:
    STX TEXT_PTR
    LDX DRAW_PTR
    ADX #97
    STX TEXT_OUT
    JSR TEXT
    LDX DRAW_PTR
    LDAA POSE
    STAA 129,X
    ADX #131
    LDAA CARD_VALUE
    JSR NUMBER
EMPTY_CARD_DONE:
    RTS

DRAW_REWARD:
    JSR DRAW_ORNAMENT
    LDX #REWARD_TEXT
    JSR TEXT_TABLE
    CLR INDEX
REWARD_DRAW_CARD:
    LDX #REWARD_0
    LDAB INDEX
REWARD_CARD_INDEX:
    TSTB
    BEQ REWARD_CARD_READ
    INX
    DECB
    BRA REWARD_CARD_INDEX
REWARD_CARD_READ:
    LDAA 0,X
    STAA CARD_ID
    LDX #FRAMEBUFFER + 32 * 8 + 4
    LDAB INDEX
REWARD_POSITION:
    TSTB
    BEQ REWARD_POSITION_DONE
    ADX #8
    DECB
    BRA REWARD_POSITION
REWARD_POSITION_DONE:
    STX DRAW_PTR
    JSR DRAW_CARD
    JSR CLOCK_SERVICE
    INC INDEX
    LDAA INDEX
    CMPA #3
    BCS REWARD_DRAW_CARD
    LDAA SELECTED
    CMPA #3
    BEQ DRAW_REST_ARROW
    LDX #FRAMEBUFFER + 32 * 7 + 7
    LDAB SELECTED
REWARD_ARROW_INDEX:
    TSTB
    BEQ REWARD_ARROW
    ADX #8
    DECB
    BRA REWARD_ARROW_INDEX
REWARD_ARROW:
    LDAA #$99
    STAA 0,X
    LDX #REWARD_0
    LDAB SELECTED
REWARD_DESCRIPTION_INDEX:
    TSTB
    BEQ REWARD_DESCRIPTION
    INX
    DECB
    BRA REWARD_DESCRIPTION_INDEX
REWARD_DESCRIPTION:
    LDAA 0,X
    LDX #CARD_DESCRIPTIONS
    JSR POINTER_INDEX
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 32 * 15 + 1
    STX TEXT_OUT
    JSR TEXT
    JMP PRESENT
DRAW_REST_ARROW:
    LDAA #30
    STAA FRAMEBUFFER + 32 * 18 + 4
    JMP PRESENT
DRAW_DEATH:
    JSR DRAW_ORNAMENT
    LDX #DEATH_TEXT
    JSR TEXT_TABLE
    JMP PRESENT
DRAW_WIN:
    JSR DRAW_ORNAMENT
    LDX #WIN_TEXT
    JSR TEXT_TABLE
    LDAA TOTAL_CARDS
    LDX #FRAMEBUFFER + 32 * 11 + 23
    JSR NUMBER
    LDAA HP
    LDX #FRAMEBUFFER + 32 * 14 + 23
    JSR NUMBER
    JMP PRESENT
DRAW_DECK:
    JSR CLEAR_SCREEN
    LDX #DECK_TEXT
    JSR TEXT_TABLE
    CLR INDEX
DECK_CARD_LOOP:
    LDX #FRAMEBUFFER + 32 * 6 + 1
    LDAA INDEX
    CMPA #12
    BCS DECK_FIRST_COLUMN
    SUBA #12
    ADX #16
DECK_FIRST_COLUMN:
    TAB
DECK_CARD_ROW:
    TSTB
    BEQ DECK_CARD_POSITION
    ADX #32
    DECB
    BRA DECK_CARD_ROW
DECK_CARD_POSITION:
    STX DRAW_PTR
    LDAA INDEX
    INCA
    JSR NUMBER
    LDX #DECK
    LDAB INDEX
DECK_LIST_INDEX:
    TSTB
    BEQ DECK_LIST_CARD
    INX
    DECB
    BRA DECK_LIST_INDEX
DECK_LIST_CARD:
    LDAA 0,X
    LDX #CARD_NAMES
    JSR POINTER_INDEX
    STX TEXT_PTR
    LDX DRAW_PTR
    ADX #4
    STX TEXT_OUT
    JSR TEXT
    JSR CLOCK_SERVICE
    INC INDEX
    LDAA INDEX
    CMPA DECK_COUNT
    BCS DECK_CARD_LOOP
    JMP PRESENT

ANIMATE_TITLE:
    TST MODE
    BNE TITLE_ANIM_DONE
    LDAA TICK
    SUBA ANIM_LAST
    CMPA #16
    BCS TITLE_ANIM_DONE
    LDAA TICK
    STAA ANIM_LAST
    LSRA
    LSRA
    LSRA
    LSRA
    ANDA #1
    ADDA #$9C
    STAA FRAMEBUFFER + 32 * 22 + 5
    STAA FRAMEBUFFER + 32 * 22 + 15
    STAA FRAMEBUFFER + 32 * 22 + 25
    STAA $C100 + 32 * 22 + 5
    STAA $C100 + 32 * 22 + 15
    STAA $C100 + 32 * 22 + 25
TITLE_ANIM_DONE:
    RTS

DRAW_ORNAMENT:
    LDX #FRAMEBUFFER
    LDAB #32
    LDAA #$96
ORNAMENT_HORIZONTAL:
    STAA 0,X
    INX
    DECB
    BNE ORNAMENT_HORIZONTAL
    LDX #FRAMEBUFFER + 736
    LDAB #32
ORNAMENT_BOTTOM:
    STAA 0,X
    INX
    DECB
    BNE ORNAMENT_BOTTOM
    LDX #FRAMEBUFFER + 32
    LDAB #22
    LDAA #$97
ORNAMENT_VERTICAL:
    STAA 0,X
    STAA 31,X
    ADX #32
    DECB
    BNE ORNAMENT_VERTICAL
    LDAA #$9D
    STAA FRAMEBUFFER + 32 * 2 + 3
    STAA FRAMEBUFFER + 32 * 2 + 28
    STAA FRAMEBUFFER + 32 * 21 + 3
    STAA FRAMEBUFFER + 32 * 21 + 28
    RTS

; Resolve one visible card effect before proceeding to the next one.
SIGIL_SCENE:
    PSHA
    PSHB
    STX FX_REGX
    LDX #$3340
SIGIL_SAVE:
    LDAA 0,X
    PSHA
    INX
    CPX #$3390
    BNE SIGIL_SAVE
    LDAA TICK
    STAA FX_CLOCK
    INC PACE_ACTIVE
    JSR DRAW_BATTLE
    LDAA #16
    JSR PACE_WAIT
    CLR PACE_ACTIVE
    LDAA FX_CLOCK
    STAA TICK
    LDX #$3390
SIGIL_RESTORE:
    DEX
    PULA
    STAA 0,X
    CPX #$3340
    BNE SIGIL_RESTORE
    LDX FX_REGX
    PULB
    PULA
    RTS
