GAME_START:
    CLR BATTLE
SHOW_TITLE:
    CLR MODE
    LDX #TITLE_PCG
    JSR LOAD_PCG
    LDX #MUSIC_TITLE
    JSR PLAY_MUSIC
    JSR DRAW_TITLE
    JMP FRAME_READY
IDLE:
    JSR CLOCK_SERVICE
    JSR ANIMATE_TITLE
    JSR INPUT_CAPTURE
    LDAA KEY_PENDING
    BEQ IDLE
    CLR KEY_PENDING
DISPATCH:
    STAA ACTION
    LDX #SFX_MENU
    JSR PLAY_SFX
    LDAA MODE
    BEQ TITLE_INPUT
    CMPA #1
    BEQ BATTLE_INPUT
    CMPA #2
    BEQ REWARD_INPUT
    CMPA #3
    BEQ DEFEAT_INPUT
    CMPA #4
    BEQ SHOW_TITLE
    CMPA #6
    BEQ RETURN_BATTLE
    JMP SHOW_TITLE
TITLE_INPUT:
    LDAA ACTION
    CMPA #5
    BEQ NEW_RUN
    LDAA #5
    STAA MODE
    JSR DRAW_HELP
    JMP FRAME_READY
NEW_RUN:
    JSR SOUND_STOP
    LDAA #60
    STAA HP
    CLR BATTLE
    CLR TOTAL_CARDS
    LDAA TICK
    ORAA #1
    STAA RNG
    LDAA #8
    STAA DECK_COUNT
    LDX #INITIAL_DECK
    STX SRC
    LDX #DECK
    STX DST
    LDX #8
    STX COUNT
    JSR COPY
    LDX #MUSIC_BATTLE
    JSR PLAY_MUSIC
START_BATTLE:
    CLR SHIELD
    CLR ENEMY_SHIELD
    CLR POISON
    CLR WEAK
    CLR VULNERABLE
    CLR STRENGTH
    CLR THORNS
    CLR ECHO
    CLR RETAIN
    CLR DISCARD_COUNT
    CLR EXHAUST_COUNT
    CLR SELECTED
    CLR TURN
    LDAA #1
    STAA MODE
    LDAA DECK_COUNT
    STAA DRAW_COUNT
    TAB
    LDX #DECK
    STX SRC
    LDX #DRAW_PILE
    STX DST
    CLRA
    STAA COUNT
    STAB COUNT + 1
    JSR COPY
    LDX #BATTLE_ORDER
    LDAB BATTLE
START_BATTLE_INDEX:
    TSTB
    BEQ START_BATTLE_READ
    INX
    DECB
    BRA START_BATTLE_INDEX
START_BATTLE_READ:
    LDAA 0,X
    STAA ENEMY_ID
    ANDA #1
    STAA INTENT
    LDX #ENEMY_STATS
    LDAB ENEMY_ID
ENEMY_STATS_INDEX:
    TSTB
    BEQ ENEMY_STATS_READ
    ADX #3
    DECB
    BRA ENEMY_STATS_INDEX
ENEMY_STATS_READ:
    LDAA 0,X
    STAA ENEMY_HP
    LDAA 1,X
    STAA ENEMY_ATTACK
    LDAA 2,X
    STAA ENEMY_GUARD
    JSR LOAD_ENEMY_PCG
    LDAA #255
    LDX #HAND
    STAA 0,X
    STAA 1,X
    STAA 2,X
    STAA 3,X
    JSR PLAYER_TURN
    JSR QUEUE_START
    JMP REDRAW
BATTLE_INPUT:
    LDAA ACTION
    CMPA #3
    BEQ SELECT_LEFT
    CMPA #4
    BEQ SELECT_RIGHT
    CMPA #6
    BEQ SELECT_END
    CMPA #1
    BEQ SHOW_DECK
    CMPA #5
    BNE IDLE
    LDAA SELECTED
    CMPA #4
    BEQ BATTLE_END_TURN
    JSR PLAY_CARD
    JMP REDRAW
BATTLE_END_TURN:
    JSR ENEMY_TURN
    JMP REDRAW
SELECT_END:
    LDAA #4
    STAA SELECTED
    JMP REDRAW
SELECT_LEFT:
    DEC SELECTED
    BPL REDRAW
    LDAA #4
    STAA SELECTED
    JMP REDRAW
SELECT_RIGHT:
    INC SELECTED
    LDAA SELECTED
    CMPA #5
    BCS REDRAW
    CLR SELECTED
    JMP REDRAW
SHOW_DECK:
    LDAA #6
    STAA MODE
    JSR DRAW_DECK
    JMP FRAME_READY
RETURN_BATTLE:
    LDAA #1
    STAA MODE
    JMP REDRAW
REWARD_INPUT:
    LDAA ACTION
    CMPA #3
    BEQ REWARD_LEFT
    CMPA #4
    BEQ REWARD_RIGHT
    CMPA #5
    BNE IDLE
    LDAA SELECTED
    CMPA #3
    BEQ REWARD_REST
    LDX #REWARD_0
    LDAB SELECTED
REWARD_SELECT_INDEX:
    TSTB
    BEQ REWARD_ADD
    INX
    DECB
    BRA REWARD_SELECT_INDEX
REWARD_ADD:
    LDAA 0,X
    LDX #DECK
    LDAB DECK_COUNT
REWARD_DECK_INDEX:
    TSTB
    BEQ REWARD_DECK_STORE
    INX
    DECB
    BRA REWARD_DECK_INDEX
REWARD_DECK_STORE:
    STAA 0,X
    INC DECK_COUNT
    BRA REWARD_CONTINUE
REWARD_REST:
    LDAA #10
    JSR HEAL_PLAYER
REWARD_CONTINUE:
    LDAA #4
    JSR HEAL_PLAYER
    INC BATTLE
    JMP START_BATTLE
REWARD_LEFT:
    DEC SELECTED
    BPL REDRAW
    LDAA #3
    STAA SELECTED
    JMP REDRAW
REWARD_RIGHT:
    INC SELECTED
    LDAA SELECTED
    CMPA #4
    BCS REDRAW
    CLR SELECTED
    JMP REDRAW
DEFEAT_INPUT:
    LDAA ACTION
    CMPA #5
    BEQ REQUEST_RESET
    CMPA #6
    BEQ SHOW_TITLE
    JMP IDLE
REDRAW:
    JSR DRAW_BATTLE
FRAME_READY:
    JMP IDLE

CHECK_VICTORY:
    TST HP
    BNE CHECK_ENEMY
    LDAA #3
    STAA MODE
    JMP QUEUE_LOSE
CHECK_ENEMY:
    TST ENEMY_HP
    BNE VICTORY_DONE
    CLR SELECTED
    LDAA BATTLE
    CMPA #9
    BEQ RUN_WON
    LDAA #2
    STAA MODE
    JSR RANDOM_CARD
    STAA REWARD_0
REWARD_SECOND:
    JSR RANDOM_CARD
    CMPA REWARD_0
    BEQ REWARD_SECOND
    STAA REWARD_1
REWARD_THIRD:
    JSR RANDOM_CARD
    CMPA REWARD_0
    BEQ REWARD_THIRD
    CMPA REWARD_1
    BEQ REWARD_THIRD
    STAA REWARD_2
    BRA VICTORY_SOUND
RUN_WON:
    LDAA #4
    STAA MODE
VICTORY_SOUND:
    JSR QUEUE_CLEAR
VICTORY_DONE:
    RTS

REQUEST_RESET:
    JSR CONFIRM_RESET
    TSTA
    BEQ REDRAW
    JMP NEW_RUN
