TEXT_TABLE:
    STX TABLE_PTR
TEXT_TABLE_NEXT:
    LDX TABLE_PTR
    LDAA 0,X
    ORAA 1,X
    BEQ TEXT_TABLE_DONE
    LDX 0,X
    STX TEXT_OUT
    LDX TABLE_PTR
    LDX 2,X
    STX TEXT_PTR
    JSR TEXT
    LDX TABLE_PTR
    ADX #4
    STX TABLE_PTR
    BRA TEXT_TABLE_NEXT
TEXT_TABLE_DONE:
    RTS
POINTER_INDEX:
    ASLA
    TAB
POINTER_LOOP:
    TSTB
    BEQ POINTER_READ
    INX
    DECB
    BRA POINTER_LOOP
POINTER_READ:
    LDX 0,X
    RTS
DRAW_TITLE:
    LDX #TITLE_SCREEN
    STX SRC
    LDX #FRAMEBUFFER
    STX DST
    LDX #768
    STX COUNT
    JSR COPY
    LDX #TITLE_TEXT
    JSR TEXT_TABLE
    JMP PRESENT
DRAW_HELP:
    JSR CLEAR_SCREEN
    LDX #HELP_TEXT
    JSR TEXT_TABLE
    JMP PRESENT
DRAW_GAME:
    JSR CLEAR_SCREEN
    LDAA MODE
    CMPA #3
    BEQ DRAW_LOST
    CMPA #4
    BEQ DRAW_WIN
    LDX #HUD_TEXT
    JSR TEXT_TABLE
    LDAA HP
    LDX #FRAMEBUFFER + 3
    JSR NUMBER
    LDAA SHIELD
    LDX #FRAMEBUFFER + 13
    JSR NUMBER
    LDAA COINS
    LDX #FRAMEBUFFER + 26
    JSR NUMBER
    LDAA MODE
    CMPA #2
    BEQ DRAW_SHOP
    CMPA #6
    BEQ DRAW_SHOP
    LDAA BATTLE
    INCA
    LDX #FRAMEBUFFER + 32 + 6
    JSR NUMBER
    LDAA TURN
    LDX #FRAMEBUFFER + 32 + 28
    JSR NUMBER
    LDAA ENEMY_HP
    LDX #FRAMEBUFFER + 32 * 4 + 2
    JSR NUMBER
    LDAA ENEMY_ATTACK
    STAA VALUE_TEMP
    LDAA TURN
    ANDA #3
    BNE DRAW_ATTACK
    INC VALUE_TEMP
    INC VALUE_TEMP
DRAW_ATTACK:
    LDAA VALUE_TEMP
    LDX #FRAMEBUFFER + 32 * 7 + 2
    JSR NUMBER
    LDAA REROLLS
    LDX #FRAMEBUFFER + 32 * 9 + 25
    JSR NUMBER
    LDAA BATTLE
    LDX #ENEMY_NAMES
    JSR POINTER_INDEX
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 32 * 2 + 9
    STX TEXT_OUT
    JSR TEXT
    LDAA BATTLE
    LDX #MONSTER_TABLE
    JSR POINTER_INDEX
    STX SRC
    LDX #FRAMEBUFFER + 32 * 3 + 12
    STX DST
    LDAA #8
    STAA DRAW_Y
MONSTER_ROW:
    LDAB #8
MONSTER_CELL:
    LDX SRC
    LDAA 0,X
    INX
    STX SRC
    LDX DST
    STAA 0,X
    INX
    STX DST
    DECB
    BNE MONSTER_CELL
    ADX #24
    STX DST
    JSR CLOCK_SERVICE
    DEC DRAW_Y
    BNE MONSTER_ROW
    LDAA MODE
    CMPA #7
    BEQ DRAW_ROLLING
    LDAA CHOICE
    LDX #CHOICE_NAMES
    JSR POINTER_INDEX
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 32 * 20 + 13
    STX TEXT_OUT
    JSR TEXT
    BRA DRAW_DICE
DRAW_ROLLING:
    LDX #ROLLING_TEXT
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 32 * 20 + 6
    STX TEXT_OUT
    JSR TEXT
    BRA DRAW_DICE
DRAW_SHOP:
    JSR CLEAR_SCREEN
    LDX #SHOP_TEXT
    JSR TEXT_TABLE
    LDAA HP
    LDX #FRAMEBUFFER + 3
    JSR NUMBER
    LDAA SHIELD
    LDX #FRAMEBUFFER + 13
    JSR NUMBER
    LDAA COINS
    LDX #FRAMEBUFFER + 26
    JSR NUMBER
    CLR INDEX
    LDX #FRAMEBUFFER + 32 * 4 + 6
    STX DRAW_PTR
SHOP_FACE_ROW:
    LDAA INDEX
    LDX #FACES
    JSR BYTE_INDEX
    LDAA 0,X
    LDX DRAW_PTR
    JSR NUMBER
    LDX DRAW_PTR
    ADX #4
    STX DRAW_PTR
    INC INDEX
    LDAA INDEX
    CMPA #6
    BEQ SHOP_FACE_NEW_ROW
    CMPA #12
    BEQ SHOP_FACE_NEW_ROW
    CMPA #18
    BCS SHOP_FACE_ROW
    BRA SHOP_FACE_MARK
SHOP_FACE_NEW_ROW:
    ADX #40
    STX DRAW_PTR
    BRA SHOP_FACE_ROW
SHOP_FACE_MARK:
    LDX #FRAMEBUFFER + 32 * 3 + 7
    LDAB SELECTED
SHOP_MARK_DIE:
    TSTB
    BEQ SHOP_MARK_FACE
    ADX #64
    DECB
    BRA SHOP_MARK_DIE
SHOP_MARK_FACE:
    LDAB FACE
SHOP_MARK_INDEX:
    TSTB
    BEQ SHOP_MARK
    ADX #4
    DECB
    BRA SHOP_MARK_INDEX
SHOP_MARK:
    LDAA #54
    STAA 0,X
    LDAA MODE
    CMPA #6
    BNE DRAW_DICE
    LDX #SERVICE_TEXT
    JSR TEXT_TABLE
    LDX #FRAMEBUFFER + 32 * 19 + 2
    LDAB MENU
SERVICE_ARROW_INDEX:
    TSTB
    BEQ SERVICE_ARROW
    ADX #8
    DECB
    BRA SERVICE_ARROW_INDEX
SERVICE_ARROW:
    LDAA #54
    STAA 0,X
DRAW_DICE:
    CLR INDEX
    LDX #FRAMEBUFFER + 32 * 12 + 1
    STX DRAW_PTR
DRAW_DIE:
    LDAA MODE
    CMPA #2
    BEQ PREVIEW_DIE
    CMPA #6
    BEQ PREVIEW_DIE
    LDAA INDEX
    LDX #DICE
    JSR BYTE_INDEX
    LDAA 0,X
    STAA VALUE_TEMP
    LDAA MODE
    CMPA #7
    BNE DRAW_USED_CHECK
    LDAA INDEX
    LDX #BIT_MASKS
    JSR BYTE_INDEX
    LDAA 0,X
    BITA ROLL_MASK
    BEQ DRAW_USED_CHECK
    LDAA ROLL_COUNT
    STAA VALUE_TEMP
DRAW_USED_CHECK:
    LDAA INDEX
    LDX #BIT_MASKS
    JSR BYTE_INDEX
    LDAA 0,X
    BITA USED
    BEQ DIE_FACE
    CLR VALUE_TEMP
    BRA DIE_FACE
PREVIEW_DIE:
    LDAA INDEX
    ASLA
    STAA VALUE_TEMP
    ASLA
    ADDA VALUE_TEMP
    ADDA FACE
    LDX #FACES
    JSR BYTE_INDEX
    LDAA 0,X
    STAA VALUE_TEMP
DIE_FACE:
    LDAA VALUE_TEMP
    LDX #DICE_TABLE
    JSR POINTER_INDEX
    STX SRC
    LDX DRAW_PTR
    STX DST
    LDAA #6
    STAA DRAW_Y
DIE_ROW:
    LDAB #6
DIE_CELL:
    LDX SRC
    LDAA 0,X
    INX
    STX SRC
    LDX DST
    STAA 0,X
    INX
    STX DST
    DECB
    BNE DIE_CELL
    ADX #26
    STX DST
    DEC DRAW_Y
    BNE DIE_ROW
    LDX DRAW_PTR
    ADX #10
    STX DRAW_PTR
    JSR CLOCK_SERVICE
    INC INDEX
    LDAA INDEX
    CMPA #3
    BCS DRAW_DIE
    LDX #FRAMEBUFFER + 32 * 18 + 3
    LDAB SELECTED
DIE_ARROW_INDEX:
    TSTB
    BEQ DIE_ARROW
    ADX #10
    DECB
    BRA DIE_ARROW_INDEX
DIE_ARROW:
    LDAA #62
    STAA 0,X
    TST ERROR
    BEQ DRAW_PRESENT
    LDX #ERROR_TEXT
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 32 * 21
    STX TEXT_OUT
    JSR TEXT
DRAW_PRESENT:
    JMP PRESENT
DRAW_LOST:
    LDX #LOST_TEXT
    JSR TEXT_TABLE
    JMP PRESENT
DRAW_WIN:
    LDX #WIN_TEXT
    JSR TEXT_TABLE
    JMP PRESENT
