; Blocking presentation: combat state is advanced only by the caller.
; Discard input during each scene and retain all three assigned dice until
; the attack, shield absorption and HP loss have each been shown.
SHOW_EFFECT:
    STAA EVENT_KIND
    CLR EVENT_FRAME
    INC PACE_ACTIVE
    CMPA #1
    BEQ EFFECT_SWING
    CMPA #5
    BEQ EFFECT_SWING
    CMPA #8
    BEQ EFFECT_BREAK
    CMPA #10
    BNE EFFECT_DRAW
EFFECT_BREAK:
    LDX #SFX_DEATH
    JSR PLAY_SFX
    BRA EFFECT_DRAW
EFFECT_SWING:
    LDX #SFX_SWING
    JSR PLAY_SFX
EFFECT_DRAW:
    JSR DRAW_GAME
EFFECT_VISIBLE:
    LDAA #8
    JSR PACE_WAIT
    INC EVENT_FRAME
    LDAA EVENT_FRAME
    CMPA #3
    BCS EFFECT_DRAW
    LDAA #18
    JSR PACE_WAIT
    CLR EVENT_KIND
    CLR PACE_ACTIVE
    RTS

DRAW_FIGURE:
    LDAA #8
    STAA DRAW_Y
FIGURE_ROW:
    LDAB #8
FIGURE_CELL:
    LDX SRC
    LDAA 0,X
    INX
    STX SRC
    JSR FIGURE_FILTER
    LDX DST
    STAA 0,X
    INX
    STX DST
    DECB
    BNE FIGURE_CELL
    ADX #24
    STX DST
    JSR CLOCK_SERVICE
    DEC DRAW_Y
    BNE FIGURE_ROW
    RTS
FIGURE_FILTER:
    PSHA
    TST FIGURE_SIDE
    BNE FIGURE_HERO
    LDAA EVENT_KIND
    CMPA #9
    BEQ FIGURE_BLANK
    CMPA #8
    BEQ FIGURE_DISSOLVE
    CMPA #2
    BRA FIGURE_FLASH_CHECK
FIGURE_HERO:
    LDAA EVENT_KIND
    CMPA #10
    BEQ FIGURE_DISSOLVE
    CMPA #7
FIGURE_FLASH_CHECK:
    BNE FIGURE_NORMAL
    LDAA EVENT_FRAME
    CMPA #1
    BEQ FIGURE_BLANK
FIGURE_NORMAL:
    PULA
    RTS
FIGURE_DISSOLVE:
    LDAA EVENT_FRAME
    BEQ FIGURE_FADE_ONE
    CMPA #1
    BEQ FIGURE_FADE_TWO
FIGURE_BLANK:
    PULA
    LDAA #128
    RTS
FIGURE_FADE_ONE:
    PULA
    ANDA #$87
    RTS
FIGURE_FADE_TWO:
    PULA
    ANDA #$81
    RTS

DRAW_FEEDBACK:
    TST EVENT_KIND
    BEQ FEEDBACK_DONE
    LDX #FRAMEBUFFER + 20 * 32
    LDAB #64
    LDAA #64
FEEDBACK_CLEAR:
    STAA 0,X
    INX
    DECB
    BNE FEEDBACK_CLEAR
    LDAA EVENT_KIND
    LDX #EVENT_NAMES
    JSR POINTER_INDEX
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 20 * 32 + 1
    STX TEXT_OUT
    JSR TEXT
    LDAA EVENT_KIND
    CMPA #8
    BCC FEEDBACK_SPARK
    LDAA EVENT_VALUE
    LDX #FRAMEBUFFER + 20 * 32 + 27
    JSR NUMBER
    LDAA EVENT_KIND
    CMPA #1
    BEQ PLAYER_BOLT
    CMPA #5
    BEQ ENEMY_BOLT
    LDX #CHANGE_TEXT
    CMPA #6
    BNE FEEDBACK_CHANGE
    LDX #BLOCK_TEXT
FEEDBACK_CHANGE:
    JSR TEXT_TABLE
    LDAA EVENT_BEFORE
    LDX #FRAMEBUFFER + 21 * 32 + 8
    JSR NUMBER
    LDAA EVENT_AFTER
    LDX #FRAMEBUFFER + 21 * 32 + 25
    JSR NUMBER
    LDAA EVENT_KIND
    CMPA #3
    BEQ FEEDBACK_SHIELD
    CMPA #6
    BEQ FEEDBACK_SHIELD
    CMPA #4
    BEQ FEEDBACK_HEAL
FEEDBACK_SPARK:
    LDX #FRAMEBUFFER + 6 * 32 + 15
    LDAA EVENT_KIND
    CMPA #7
    BEQ SPARK_HERO
    CMPA #9
    BNE SPARK_DRAW
SPARK_HERO:
    ADX #11
SPARK_DRAW:
    LDAA EVENT_FRAME
    CMPA #1
    BNE FEEDBACK_DONE
    LDAA #10
    STAA 0,X
    RTS
PLAYER_BOLT:
    LDAA #2
    SUBA EVENT_FRAME
    LDX #FRAMEBUFFER + 6 * 32 + 20
    JSR BYTE_INDEX
    LDAA #28
    STAA 0,X
    LDAA #13
    STAA 1,X
    RTS
ENEMY_BOLT:
    LDAA EVENT_FRAME
    LDX #FRAMEBUFFER + 6 * 32 + 20
    JSR BYTE_INDEX
    LDAA #30
    STAA 0,X
    RTS
FEEDBACK_SHIELD:
    LDX #FRAMEBUFFER + 6 * 32 + 22
    LDAA #145
    STAA 0,X
    STAA 32,X
    TST EVENT_FRAME
    BEQ FEEDBACK_DONE
    STAA 64,X
    STAA FRAMEBUFFER + 5 * 32 + 22
    LDAA EVENT_FRAME
    CMPA #2
    BNE FEEDBACK_DONE
    LDAA #144
    STAA 96,X
    STAA FRAMEBUFFER + 4 * 32 + 22
    RTS
FEEDBACK_HEAL:
    LDAA EVENT_FRAME
    ASLA
    LDX #HEAL_POSITIONS
    JSR BYTE_INDEX
    LDX 0,X
    LDAA #11
    STAA 0,X
FEEDBACK_DONE:
    RTS
HEAL_POSITIONS:
    .word FRAMEBUFFER + 9 * 32 + 27
    .word FRAMEBUFFER + 6 * 32 + 25
    .word FRAMEBUFFER + 3 * 32 + 28
