GAME_START:
SHOW_TITLE:
    CLR MODE
    LDX #TITLE_PCG
    JSR LOAD_PCG
    LDX #MUSIC_TITLE
    JSR PLAY_MUSIC
    JSR DRAW_TITLE
    JMP FRAME_READY
IDLE:
    JSR CLOCK_SERVICE
    LDAA MODE
    CMPA #7
    BNE INPUT_READY
    JSR ROLL_TICK
INPUT_READY:
    JSR INPUT_CAPTURE
    LDAA KEY_PENDING
    BEQ IDLE
    CLR KEY_PENDING
DISPATCH:
    STAA ACTION
    CLR ERROR
    LDAA MODE
    BEQ TITLE_INPUT
    CMPA #1
    BEQ BATTLE_INPUT
    CMPA #2
    BEQ SHOP_INPUT
    CMPA #3
    BEQ LOST_INPUT
    CMPA #7
    BEQ FRAME_READY
    CMPA #6
    BEQ SHOP_MENU_INPUT
    JMP SHOW_TITLE
TITLE_INPUT:
    LDAA ACTION
    CMPA #5
    BEQ NEW_GAME
    LDAA #5
    STAA MODE
    JSR DRAW_HELP
    JMP FRAME_READY
NEW_GAME:
    CLR EVENT_KIND
    CLR BATTLE
    CLR COINS
    LDAA #42
    STAA HP
    LDAA TICK
    ORAA #1
    STAA RNG
    LDX #INITIAL_FACES
    STX SRC
    LDX #FACES
    STX DST
    LDX #18
    STX COUNT
    JSR COPY
    LDX #GAME_PCG
    JSR LOAD_PCG
    LDX #MUSIC_BATTLE
    JSR PLAY_MUSIC
NEW_BATTLE:
    JSR QUEUE_START
    LDAA BATTLE
    ASLA
    LDX #ENEMY_STATS
    JSR BYTE_INDEX
    LDAA 0,X
    STAA ENEMY_HP
    LDAA 1,X
    STAA ENEMY_ATTACK
    CLR TURN
    CLR SHIELD
    CLR SELECTED
    CLR CHOICE
    LDAA #1
    STAA MODE
NEW_TURN:
    INC TURN
    CLR USED
    CLR ROLES
    CLR ROLES + 1
    CLR ROLES + 2
    LDAA #1
    STAA REROLLS
    CLR INDEX
ROLL_ALL:
    JSR ROLL_DIE
    INC INDEX
    LDAA INDEX
    CMPA #3
    BCS ROLL_ALL
    LDAA #7
    STAA ROLL_MASK
    JMP START_ROLL
RANDOM:
    LDAA RNG
    ASLA
    BCC RNG_STORE
    EORA #$1D
RNG_STORE:
    STAA RNG
    RTS
ROLL_DIE:
    JSR RANDOM
ROLL_MOD:
    CMPA #6
    BCS ROLL_FACE
    SUBA #6
    BRA ROLL_MOD
ROLL_FACE:
    STAA FACE_OFFSET
    LDAA INDEX
    ASLA
    STAA VALUE_TEMP
    ASLA
    ADDA VALUE_TEMP
    ADDA FACE_OFFSET
    LDX #FACES
    JSR BYTE_INDEX
    LDAA 0,X
    STAA VALUE_TEMP
    LDAA INDEX
    LDX #DICE
    JSR BYTE_INDEX
    LDAA VALUE_TEMP
    STAA 0,X
    RTS
BYTE_INDEX:
    TAB
BYTE_LOOP:
    TSTB
    BEQ BYTE_DONE
    INX
    DECB
    BRA BYTE_LOOP
BYTE_DONE:
    RTS
BATTLE_INPUT:
    LDAA ACTION
    CMPA #3
    BEQ SELECT_LEFT
    CMPA #4
    BEQ SELECT_RIGHT
    CMPA #1
    BEQ CHOICE_UP
    CMPA #2
    BEQ CHOICE_DOWN
    CMPA #5
    BEQ USE_DIE
    JMP FRAME_READY
SELECT_LEFT:
    DEC SELECTED
    BPL REDRAW
    LDAA #2
    STAA SELECTED
    JMP REDRAW
SELECT_RIGHT:
    INC SELECTED
    LDAA SELECTED
    CMPA #3
    BCS REDRAW
    CLR SELECTED
    JMP REDRAW
CHOICE_UP:
    DEC CHOICE
    BPL REDRAW
    LDAA #3
    STAA CHOICE
    JMP REDRAW
CHOICE_DOWN:
    INC CHOICE
    LDAA CHOICE
    CMPA #4
    BCS REDRAW
    CLR CHOICE
    JMP REDRAW
USE_DIE:
    LDAA SELECTED
    LDX #BIT_MASKS
    JSR BYTE_INDEX
    LDAA 0,X
    BITA USED
    BNE INVALID
    STAA VALUE_TEMP
    LDAA CHOICE
    CMPA #3
    BEQ REROLL
    LDAA VALUE_TEMP
    ORAA USED
    STAA USED
    LDAA SELECTED
    STAA EVENT_DIE
    LDX #ROLES
    JSR BYTE_INDEX
    LDAA CHOICE
    INCA
    STAA 0,X
    LDAA SELECTED
    LDX #DICE
    JSR BYTE_INDEX
    LDAA 0,X
    STAA ACTION_VALUE
    STAA EVENT_VALUE
    LDAA CHOICE
    BEQ ATTACK
    CMPA #1
    BEQ GUARD
    LDAA HP
    STAA EVENT_BEFORE
    ADDA ACTION_VALUE
    CMPA #42
    BLS HEAL_STORE
    LDAA #42
HEAL_STORE:
    STAA HP
    STAA EVENT_AFTER
    SUBA EVENT_BEFORE
    STAA EVENT_VALUE
    LDX #SFX_HEAL
    JSR PLAY_SFX
    LDAA #4
    JSR SHOW_EFFECT
    BRA USED_CHECK
GUARD:
    LDAA SHIELD
    STAA EVENT_BEFORE
    ADDA ACTION_VALUE
    STAA SHIELD
    STAA EVENT_AFTER
    LDX #SFX_GUARD
    JSR PLAY_SFX
    LDAA #3
    JSR SHOW_EFFECT
    BRA USED_CHECK
ATTACK:
    LDAA #1
    JSR SHOW_EFFECT
    LDAA ENEMY_HP
    STAA EVENT_BEFORE
    SUBA ACTION_VALUE
    BHI ATTACK_STORE
    CLRA
ATTACK_STORE:
    STAA ENEMY_HP
    STAA EVENT_AFTER
    LDAA EVENT_BEFORE
    SUBA EVENT_AFTER
    STAA EVENT_VALUE
    LDX #SFX_HIT
    JSR PLAY_SFX
    LDAA #2
    JSR SHOW_EFFECT
    TST ENEMY_HP
    BEQ VICTORY
USED_CHECK:
    LDAA USED
    CMPA #7
    BNE AUTO_SELECT
    LDAA TURN
    ANDA #3
    BNE NORMAL_HIT
    LDAA ENEMY_ATTACK
    ADDA #2
    BRA ENEMY_HIT
NORMAL_HIT:
    LDAA ENEMY_ATTACK
ENEMY_HIT:
    STAA ATTACK_TOTAL
    STAA EVENT_VALUE
    SUBA SHIELD
    BHI DAMAGE_READY
    CLRA
DAMAGE_READY:
    STAA DAMAGE
    LDAA #5
    JSR SHOW_EFFECT
    TST SHIELD
    BEQ APPLY_DAMAGE
    LDAA ATTACK_TOTAL
    STAA EVENT_BEFORE
    SUBA DAMAGE
    STAA EVENT_VALUE
    LDAA DAMAGE
    STAA EVENT_AFTER
    LDX #SFX_GUARD
    JSR PLAY_SFX
    LDAA #6
    JSR SHOW_EFFECT
APPLY_DAMAGE:
    TST DAMAGE
    BEQ ENEMY_BLOCKED
    LDAA HP
    STAA EVENT_BEFORE
    SUBA DAMAGE
    BHI DAMAGE_STORE
    CLRA
DAMAGE_STORE:
    STAA HP
    STAA EVENT_AFTER
    LDAA EVENT_BEFORE
    SUBA EVENT_AFTER
    STAA EVENT_VALUE
    LDX #SFX_DAMAGE
    JSR PLAY_SFX
    LDAA #7
    JSR SHOW_EFFECT
    TST HP
    BEQ DEFEAT
ENEMY_BLOCKED:
    CLR SHIELD
    JMP NEW_TURN
AUTO_SELECT:
    LDAA SELECTED
    INCA
    CMPA #3
    BCS AUTO_STORE
    CLRA
AUTO_STORE:
    STAA SELECTED
    LDX #BIT_MASKS
    JSR BYTE_INDEX
    LDAA 0,X
    BITA USED
    BNE AUTO_SELECT
    JMP REDRAW
REROLL:
    TST REROLLS
    BEQ INVALID
    DEC REROLLS
    LDAA SELECTED
    STAA INDEX
    JSR ROLL_DIE
    LDAA SELECTED
    LDX #BIT_MASKS
    JSR BYTE_INDEX
    LDAA 0,X
    STAA ROLL_MASK
START_ROLL:
    LDAA #6
    STAA ROLL_COUNT
    LDAA TICK
    STAA ANIM_LAST
    LDAA #7
    STAA MODE
    LDX #SFX_ROLL
    JSR PLAY_SFX
    JMP REDRAW
ROLL_TICK:
    LDAA TICK
    SUBA ANIM_LAST
    CMPA #4
    BCS ROLL_DONE
    LDAA TICK
    STAA ANIM_LAST
    DEC ROLL_COUNT
    BNE ROLL_DRAW
    LDAA #1
    STAA MODE
ROLL_DRAW:
    JSR DRAW_GAME
ROLL_DONE:
    RTS
INVALID:
    LDAA #1
    STAA ERROR
    LDX #SFX_EMPTY
    JSR PLAY_SFX
    JMP REDRAW
VICTORY:
    CLR ENEMY_HP
    LDAA #8
    JSR SHOW_EFFECT
    LDAA HP
    ADDA #2
    CMPA #42
    BLS VICTORY_HEAL
    LDAA #42
VICTORY_HEAL:
    STAA HP
    LDAA COINS
    ADDA #3
    STAA COINS
    LDAA #9
    JSR SHOW_EFFECT
    CLR SELECTED
    CLR FACE
    CLR MENU
    LDAA #2
    STAA MODE
    JSR QUEUE_CLEAR
    LDAA BATTLE
    CMPA #8
    BNE REDRAW
    LDAA #4
    STAA MODE
    JMP REDRAW
DEFEAT:
    CLR HP
    LDAA #10
    JSR SHOW_EFFECT
    LDAA #3
    STAA MODE
    JSR QUEUE_LOSE
    JMP REDRAW
LOST_INPUT:
    LDAA ACTION
    CMPA #5
    BEQ REQUEST_RESET
    JMP SHOW_TITLE
SHOP_INPUT:
    LDAA ACTION
    CMPA #3
    BEQ SELECT_LEFT
    CMPA #4
    BEQ SELECT_RIGHT
    CMPA #1
    BEQ FACE_UP
    CMPA #2
    BEQ FACE_DOWN
    CMPA #5
    BNE FRAME_READY
    LDAA #6
    STAA MODE
    CLR MENU
    JMP REDRAW
FACE_UP:
    DEC FACE
    BPL REDRAW
    LDAA #5
    STAA FACE
    JMP REDRAW
FACE_DOWN:
    INC FACE
    LDAA FACE
    CMPA #6
    BCS REDRAW
    CLR FACE
    JMP REDRAW
SHOP_MENU_INPUT:
    LDAA ACTION
    CMPA #3
    BEQ SHOP_LEFT
    CMPA #4
    BEQ SHOP_RIGHT
    CMPA #6
    BEQ SHOP_CLOSE
    CMPA #5
    BNE FRAME_READY
    LDAA MENU
    BEQ BUY_FACE
    CMPA #1
    BEQ BUY_HEAL
    CMPA #2
    BEQ SHOP_NEXT
SHOP_CLOSE:
    LDAA #2
    STAA MODE
    JMP REDRAW
SHOP_LEFT:
    DEC MENU
    BPL REDRAW
    LDAA #3
    STAA MENU
    JMP REDRAW
SHOP_RIGHT:
    INC MENU
    LDAA MENU
    CMPA #4
    BCS REDRAW
    CLR MENU
    JMP REDRAW
FACE_POINTER:
    LDAA SELECTED
    ASLA
    STAA VALUE_TEMP
    ASLA
    ADDA VALUE_TEMP
    ADDA FACE
    LDX #FACES
    JMP BYTE_INDEX
BUY_FACE:
    LDAA COINS
    CMPA #3
    BCS INVALID
    JSR FACE_POINTER
    LDAA 0,X
    CMPA #9
    BCC INVALID
    ADDA #2
    CMPA #9
    BLS FACE_STORE
    LDAA #9
FACE_STORE:
    STAA 0,X
    LDAA COINS
    SUBA #3
    STAA COINS
    LDX #SFX_FORGE
    JSR PLAY_SFX
    BRA SHOP_CLOSE
BUY_HEAL:
    LDAA COINS
    CMPA #2
    BCS INVALID
    LDAA HP
    CMPA #42
    BEQ INVALID
    ADDA #6
    CMPA #42
    BLS SHOP_HEAL
    LDAA #42
SHOP_HEAL:
    STAA HP
    LDAA COINS
    SUBA #2
    STAA COINS
    LDX #SFX_HEAL
    JSR PLAY_SFX
    BRA SHOP_CLOSE
SHOP_NEXT:
    INC BATTLE
    JMP NEW_BATTLE
REDRAW:
    JSR DRAW_GAME
FRAME_READY:
    JMP IDLE
BIT_MASKS:
    .byte 1,2,4
INITIAL_FACES:
    .byte 1,2,3,4,5,6,1,2,3,4,5,6,1,2,3,4,5,6

REQUEST_RESET:
    JSR CONFIRM_RESET
    TSTA
    BEQ REDRAW
    JMP NEW_GAME
