; Ranked puzzle campaigns. BEST survives retries, title and stage selection.
; ENTRY clears it on program launch; no ROM or browser storage is written.
MODE: .equ $3340
LEVEL: .equ $3341
ACTION: .equ $3342
N_LAST: .equ $3343
N_TMP: .equ $3344
N_ACC: .equ $3345
N_ARG0: .equ $3346
N_ARG1: .equ $3347
N_ARG2: .equ $3348
N_PCG: .equ $3349
N_PTR: .equ $334A
C_CELL: .equ $334C
C_COL: .equ $334D
C_ROW: .equ $334E
C_STARS: .equ $334F
C_TOTAL: .equ $3350
B_ARRAY: .equ $3600
C_ARRAY: .equ $3680
D_ARRAY: .equ $3700
BEST: .equ $3780

GAME_START:
SHOW_TITLE:
    CLR MODE
    LDX #TITLE_PCG
    JSR LOAD_PCG
    LDX #MUSIC_TITLE
    JSR PLAY_MUSIC
    LDX #TITLE_SCREEN
    JSR N_SCREEN
    JSR P_SHOW_CODE
    JMP C_PRESENT
IDLE:
    JSR CLOCK_SERVICE
    JSR INPUT_CAPTURE
    LDAA KEY_PENDING
    BNE DISPATCH
    BRA IDLE
DISPATCH:
    STAA ACTION
    CLR KEY_PENDING
    LDAA MODE
    CMPA #7
    BEQ P_INPUT
    CMPA #5
    BEQ SHOW_TITLE
    CMPA #6
    BEQ C_SELECT_INPUT
    LDAB ACTION
    CMPB #8
    BEQ C_REQUEST_SELECT
    TSTA
    BEQ C_TITLE_INPUT
    CMPB #6
    BEQ N_RETRY
    CMPA #1
    BEQ C_GAME_INPUT
    CMPB #5
    BNE FRAME_READY
    CMPA #2
    BEQ N_ADVANCE
    JMP SHOW_TITLE
C_TITLE_INPUT:
    CMPB #7
    BEQ P_OPEN
    CMPB #5
    BEQ N_NEW_LEVEL
    LDAA #5
    STAA MODE
    LDX #HELP_SCREEN
    JSR N_SCREEN
    JMP FRAME_READY
C_GAME_INPUT:
    JSR FN_ACT
    JMP N_DRAW
N_RETRY:
    JSR CONFIRM_RESET
    TSTA
    BEQ N_DRAW
N_NEW_LEVEL:
    LDX #$3400
    CLRA
C_CLEAR:
    STAA 0,X
    INX
    CPX #BEST
    BNE C_CLEAR
    LDAA #1
    STAA MODE
    JSR SOUND_STOP
    LDX #GAME_PCG
    JSR LOAD_PCG
    LDAA LEVEL
    ASLA
    LDX #N_LEVEL_TABLE
    JSR N_INDEX
    LDX 0,X
    STX SRC
    LDX #D_ARRAY
    STX DST
    LDAB #32
C_UNPACK:
    LDX SRC
    LDAA 0,X
    INX
    STX SRC
    STAA N_TMP
    LSRA
    LSRA
    LSRA
    LSRA
    LDX DST
    STAA 0,X
    LDAA N_TMP
    ANDA #15
    STAA 1,X
    INX
    INX
    STX DST
    DECB
    BNE C_UNPACK
    LDX #6
    STX COUNT
    JSR COPY
    JSR FN_INIT
    JMP N_DRAW
N_ADVANCE:
    INC LEVEL
    LDAA LEVEL
    CMPA #GAME_LEVELS
    BCS N_NEW_LEVEL
    DEC LEVEL
    LDAA #4
    STAA MODE
N_DRAW:
    LDX #HUD_SCREEN
    STX SRC
    LDX #FRAMEBUFFER
    STX DST
    LDX #768
    STX COUNT
    JSR COPY
    JSR FN_DRAW
    LDAA LEVEL
    INCA
    LDX #FRAMEBUFFER + 29
    JSR NUMBER
    LDAA LEVEL
    LDX #BEST
    JSR N_INDEX
    LDAA 0,X
    STAA C_STARS
    LDX #FRAMEBUFFER + 21 * 32 + 6
    JSR C_STAR_ROW
    LDAA MODE
    CMPA #1
    BEQ C_PRESENT
    LDAA RANK_STARS
    STAA C_STARS
    LDX #FRAMEBUFFER + 21 * 32 + 23
    JSR C_STAR_ROW
    LDX #STATUS_CLEAR
    LDAA MODE
    CMPA #2
    BEQ C_STATUS
    LDX #STATUS_END
C_STATUS:
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 22 * 32 + 1
    STX TEXT_OUT
    JSR TEXT
C_PRESENT:
    JSR PRESENT
FRAME_READY:
    JMP IDLE
N_SCREEN:
    STX SRC
    LDX #FRAMEBUFFER
    STX DST
    LDX #768
    STX COUNT
    JSR COPY
    JMP PRESENT

N_WIN:
    LDAA LEVEL
    LDX #BEST
    JSR N_INDEX
    LDAA RANK_STARS
    CMPA 0,X
    BLS C_KEEP_BEST
    STAA 0,X
C_KEEP_BEST:
    LDAA #2
    STAA MODE
    STAA N_ARG0
    JMP N_SOUND

C_SELECT:
    LDAA #6
    STAA MODE
    LDX #GAME_PCG
    JSR LOAD_PCG
    JSR CLEAR_SCREEN
    LDX #SELECT_HEADER
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 2
    STX TEXT_OUT
    JSR TEXT
    CLR C_CELL
    CLR C_COL
    CLR C_TOTAL
    LDAA #3
    STAA C_ROW
C_SELECT_CELL:
    LDAA C_COL
    STAA N_ARG0
    LDAA C_ROW
    STAA N_ARG1
    JSR N_XY
    STX N_PTR
    LDAA C_CELL
    INCA
    JSR NUMBER
    LDX N_PTR
    LDAA #64
    LDAB C_CELL
    CMPB LEVEL
    BNE C_NOT_SELECTED
    LDAA #30
C_NOT_SELECTED:
    STAA 0,X
    LDAA C_CELL
    LDX #BEST
    JSR N_INDEX
    LDAA 0,X
    STAA C_STARS
    ADDA C_TOTAL
    STAA C_TOTAL
    LDX N_PTR
    INX
    INX
    INX
    JSR C_STAR_ROW
    INC C_CELL
    LDAA C_COL
    ADDA #6
    STAA C_COL
    CMPA #30
    BCS C_SELECT_NEXT
    CLR C_COL
    INC C_ROW
    INC C_ROW
C_SELECT_NEXT:
    LDAA C_CELL
    CMPA #GAME_LEVELS
    BCS C_SELECT_CELL
    LDX #SELECT_FOOTER
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 19 * 32 + 1
    STX TEXT_OUT
    JSR TEXT
    LDAA C_TOTAL
    LDX #FRAMEBUFFER + 19 * 32 + 13
    JSR NUMBER
    LDX #SELECT_PAR
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 20 * 32 + 1
    STX TEXT_OUT
    JSR TEXT
    LDAA LEVEL
    INCA
    LDX #FRAMEBUFFER + 20 * 32 + 7
    JSR NUMBER
    LDAA LEVEL
    ASLA
    LDX #N_LEVEL_TABLE
    JSR N_INDEX
    LDX 0,X
    LDAA 37,X
    LDX #FRAMEBUFFER + 20 * 32 + 17
    JSR NUMBER
    LDX #SELECT_CONTROLS
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 21 * 32 + 1
    STX TEXT_OUT
    JSR TEXT
    LDX #SELECT_EXIT
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 23 * 32 + 1
    STX TEXT_OUT
    JSR TEXT
    JSR P_SHOW_CODE
    JMP C_PRESENT
C_SELECT_INPUT:
    LDAA ACTION
    CMPA #7
    BEQ P_OPEN
    CMPA #5
    BEQ N_NEW_LEVEL
    CMPA #6
    BEQ SHOW_TITLE
    CMPA #1
    BEQ C_SELECT_UP
    CMPA #2
    BEQ C_SELECT_DOWN
    CMPA #3
    BEQ C_SELECT_LEFT
    CMPA #4
    BNE FRAME_READY
    LDAA LEVEL
    INCA
    CMPA #GAME_LEVELS
    BCS C_SELECTED
    CLRA
    BRA C_SELECTED
C_SELECT_LEFT:
    LDAA LEVEL
    BNE C_SELECT_PREV
    LDAA #GAME_LEVELS
C_SELECT_PREV:
    DECA
    BRA C_SELECTED
C_SELECT_UP:
    LDAA LEVEL
    CMPA #5
    BCC C_SELECT_SUB
    ADDA #GAME_LEVELS
C_SELECT_SUB:
    SUBA #5
    BRA C_SELECTED
C_SELECT_DOWN:
    LDAA LEVEL
    ADDA #5
    CMPA #GAME_LEVELS
    BCS C_SELECTED
    SUBA #GAME_LEVELS
C_SELECTED:
    STAA LEVEL
    JMP C_SELECT
C_STAR_ROW:
    LDAB #3
C_STAR_NEXT:
    LDAA #$9D
    TST C_STARS
    BEQ C_STAR_EMPTY
    DECA
    DEC C_STARS
C_STAR_EMPTY:
    STAA 0,X
    INX
    DECB
    BNE C_STAR_NEXT
    RTS

C_REQUEST_SELECT:
    CMPA #1
    BNE C_SELECT
    JSR CONFIRM_RESET
    TSTA
    BEQ N_DRAW
    JMP C_SELECT
