; Draw an intermediate logical state and hold it for A ticks (about 60 Hz).
; Rule locals live in distinct slots from draw locals; no rule is re-entered.
MOTION_TICKS: .equ $3338
MOTION_START: .equ $3339
MOTION_ACTIVE: .equ $333A
MOTION_CLOCK: .equ $33A0
N_ANIMATE:
    CLRB
    BRA N_MOTION_ENTER
N_HOLD:
    LDAB #1
N_MOTION_ENTER:
    STAA MOTION_TICKS
    LDAA TICK
    STAA MOTION_CLOCK
    INC MOTION_ACTIVE
    TSTB
    BNE MOTION_WAIT
    JSR N_RENDER
MOTION_WAIT:
    LDAA TICK
    STAA MOTION_START
MOTION_VISIBLE:
    JSR CLOCK_SERVICE
    CLR KEY_PENDING
    LDAA TICK
    SUBA MOTION_START
    CMPA MOTION_TICKS
    BCS MOTION_VISIBLE
    CLR KEY_ACTION
    CLR MOTION_ACTIVE
    LDAA MOTION_CLOCK
    STAA TICK
    RTS
