; Progress-code scratch lies below STATE_END; no BASIC state is used.
P_CRC: .equ $3351
P_LEN: .equ $3352
P_POS: .equ $3353
P_INDEX: .equ $3354
P_PREFIX: .equ $3355
P_HEADER: .equ $3356
P_LIMIT: .equ $3357
P_CURSOR: .equ $3358
P_ERROR: .equ $3359
P_RETURN: .equ $335A
P_VALUE: .equ $335B
P_ROW: .equ $335C
P_COL: .equ $335D
P_RECORD: .equ $37A8
P_BUFFER: .equ $37D0

P_ENCODE:
    LDX #BEST
    STX SRC
    LDX #P_RECORD
    STX DST
    LDAB #20
P_PACK:
    LDX SRC
    LDAA 0,X
    ASLA
    ASLA
    ORAA 1,X
    INX
    INX
    STX SRC
    LDX DST
    STAA 0,X
    INX
    STX DST
    DECB
    BNE P_PACK
    CLR P_PREFIX
    LDX #P_RECORD
P_PREFIX_LOOP:
    LDAA 0,X
    CMPA #15
    BNE P_PREFIX_DONE
    INC P_PREFIX
    INX
    LDAA P_PREFIX
    CMPA #20
    BCS P_PREFIX_LOOP
P_PREFIX_DONE:
    LDAA #20
    STAA P_LIMIT
P_TRIM:
    LDAA P_LIMIT
    CMPA P_PREFIX
    BEQ P_HEADER_BUILD
    DECA
    LDX #P_RECORD
    JSR N_INDEX
    TST 0,X
    BNE P_HEADER_BUILD
    DEC P_LIMIT
    BRA P_TRIM
P_HEADER_BUILD:
    LDAA LEVEL
    STAA P_HEADER
    TST P_PREFIX
    BEQ P_HEADER_READY
    ORAA #128
    LDAB P_PREFIX
    CMPB #16
    BCS P_HEADER_EXT
    ORAA #64
P_HEADER_EXT:
    STAA P_HEADER
P_HEADER_READY:
    CLR P_LEN
    LSRA
    LSRA
    LSRA
    LSRA
    JSR P_PUSH
    LDAA P_HEADER
    ANDA #15
    JSR P_PUSH
    TST P_PREFIX
    BEQ P_BODY
    LDAA P_PREFIX
    ANDA #15
    JSR P_PUSH
P_BODY:
    LDAA P_PREFIX
    STAA P_INDEX
P_BODY_LOOP:
    LDAA P_INDEX
    CMPA P_LIMIT
    BEQ P_ENCODE_CRC
    LDX #P_RECORD
    JSR N_INDEX
    LDAA 0,X
    JSR P_PUSH
    INC P_INDEX
    BRA P_BODY_LOOP
P_ENCODE_CRC:
    JSR P_CRC_ALL
    LDAA P_CRC
    LSRA
    LSRA
    LSRA
    LSRA
    JSR P_PUSH
    LDAA P_CRC
    ANDA #15
    JMP P_PUSH
P_PUSH:
    STAA P_VALUE
    LDAA P_LEN
    LDX #P_BUFFER
    JSR N_INDEX
    LDAA P_VALUE
    STAA 0,X
    INC P_LEN
    RTS
P_CRC_ALL:
    LDAA #PASSWORD_TAG
    STAA P_CRC
    CLR P_POS
P_CRC_NEXT:
    LDAA P_POS
    CMPA P_LEN
    BEQ P_CRC_DONE
    LDX #P_BUFFER
    JSR N_INDEX
    LDAA 0,X
    ASLA
    ASLA
    ASLA
    ASLA
    EORA P_CRC
    LDAB #4
P_CRC_BIT:
    ASLA
    BCC P_CRC_NO_XOR
    EORA #7
P_CRC_NO_XOR:
    DECB
    BNE P_CRC_BIT
    STAA P_CRC
    INC P_POS
    BRA P_CRC_NEXT
P_CRC_DONE:
    RTS

; Render at TEXT_OUT, adding a space between groups of four letters.
P_TEXT:
    CLR P_POS
    CLR P_COL
P_TEXT_NEXT:
    LDAA P_POS
    CMPA P_LEN
    BEQ P_TEXT_DONE
    LDX #P_BUFFER
    JSR N_INDEX
    LDAA 0,X
    LDX #PASSWORD_ALPHABET
    JSR N_INDEX
    LDAA 0,X
    SUBA #32
    LDX TEXT_OUT
    STAA 0,X
    INX
    INC P_COL
    LDAA P_COL
    CMPA #4
    BNE P_TEXT_ADVANCE
    CLR P_COL
    ; Advance past the separator only when another letter follows.
    LDAA P_POS
    INCA
    CMPA P_LEN
    BEQ P_TEXT_ADVANCE
    LDAA #64
    STAA 0,X
    INX
P_TEXT_ADVANCE:
    STX TEXT_OUT
    INC P_POS
    BRA P_TEXT_NEXT
P_TEXT_DONE:
    RTS
P_SHOW_CODE:
    JSR P_ENCODE
    LDX #PASSWORD_LABEL
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 22 * 32
    STX TEXT_OUT
    JSR TEXT
    JMP P_TEXT

P_OPEN:
    LDAA MODE
    STAA P_RETURN
    LDAA #7
    STAA MODE
    CLR P_LEN
    CLR P_CURSOR
    CLR P_ERROR
    LDX #GAME_PCG
    JSR LOAD_PCG
P_DRAW:
    JSR CLEAR_SCREEN
    LDX #PASSWORD_SCREEN
    STX SRC
P_SCREEN_ROW:
    LDX SRC
    LDX 0,X
    CPX #0
    BEQ P_SCREEN_DONE
    STX TEXT_OUT
    LDX SRC
    LDX 2,X
    STX TEXT_PTR
    LDX SRC
    INX
    INX
    INX
    INX
    STX SRC
    JSR TEXT
    BRA P_SCREEN_ROW
P_SCREEN_DONE:
    LDAA P_LEN
    LDX #FRAMEBUFFER + 7 * 32 + 17
    JSR NUMBER
    LDX #FRAMEBUFFER + 6 * 32 + 3
    STX TEXT_OUT
    JSR P_TEXT
    CLR P_INDEX
    LDAA #9
    STAA P_ROW
    LDAA #2
    STAA P_COL
P_PALETTE:
    LDAA P_COL
    STAA N_ARG0
    LDAA P_ROW
    STAA N_ARG1
    JSR N_XY
    STX N_PTR
    LDAA P_INDEX
    CMPA P_CURSOR
    BNE P_NO_POINTER
    LDAA #30
    STAA 0,X
P_NO_POINTER:
    INX
    STX TEXT_OUT
    LDAA P_INDEX
    CMPA #16
    BCC P_PALETTE_COMMAND
    LDX #PASSWORD_ALPHABET
    JSR N_INDEX
    LDAA 0,X
    SUBA #32
    LDX TEXT_OUT
    STAA 0,X
    BRA P_PALETTE_NEXT
P_PALETTE_COMMAND:
    SUBA #16
    ASLA
    LDX #PASSWORD_COMMANDS
    JSR N_INDEX
    LDX 0,X
    STX TEXT_PTR
    JSR TEXT
P_PALETTE_NEXT:
    LDAA P_COL
    ADDA #7
    STAA P_COL
    CMPA #30
    BCS P_PALETTE_MORE
    LDAA #2
    STAA P_COL
    INC P_ROW
    INC P_ROW
P_PALETTE_MORE:
    INC P_INDEX
    LDAA P_INDEX
    CMPA #19
    BCS P_PALETTE
    TST P_ERROR
    BEQ P_DRAW_DONE
    LDX #PASSWORD_ERROR
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 4 * 32 + 3
    STX TEXT_OUT
    JSR TEXT
P_DRAW_DONE:
    JMP C_PRESENT
P_INPUT:
    LDAA ACTION
    CMPA #5
    BEQ P_RESTORE
    CMPA #6
    BEQ P_DELETE
    CMPA #7
    BEQ P_CANCEL
    CMPA #9
    BEQ P_CHOOSE
    CMPA #16
    BCC P_TYPE
    CMPA #1
    BEQ P_UP
    CMPA #2
    BEQ P_DOWN
    CMPA #3
    BEQ P_LEFT
    CMPA #4
    BNE FRAME_READY
    LDAA P_CURSOR
    INCA
    BRA P_WRAP_DOWN
P_DOWN:
    LDAA P_CURSOR
    ADDA #4
P_WRAP_DOWN:
    CMPA #19
    BCS P_CURSOR_SET
    SUBA #19
    BRA P_CURSOR_SET
P_UP:
    LDAA P_CURSOR
    CMPA #4
    BCC P_SUB_FOUR
    ADDA #19
P_SUB_FOUR:
    SUBA #4
    BRA P_CURSOR_SET
P_LEFT:
    LDAA P_CURSOR
    BNE P_SUB_ONE
    LDAA #19
P_SUB_ONE:
    DECA
P_CURSOR_SET:
    STAA P_CURSOR
    JMP P_DRAW
P_TYPE:
    SUBA #16
    BRA P_APPEND
P_CHOOSE:
    LDAA P_CURSOR
    CMPA #16
    BEQ P_RESTORE
    CMPA #17
    BEQ P_DELETE
    CMPA #18
    BEQ P_CANCEL
P_APPEND:
    LDAB P_LEN
    CMPB #24
    BCC P_BAD
    JSR P_PUSH
    CLR P_ERROR
    JMP P_DRAW
P_DELETE:
    TST P_LEN
    BEQ P_DRAW
    DEC P_LEN
    CLR P_ERROR
    JMP P_DRAW
P_CANCEL:
    LDAA P_RETURN
    CMPA #6
    BEQ C_SELECT
    JMP SHOW_TITLE
P_BAD:
    LDAA #1
    STAA P_ERROR
    JMP P_DRAW

P_RESTORE:
    LDAA P_LEN
    CMPA #4
    BCS P_BAD
    JSR P_CRC_ALL
    TST P_CRC
    BNE P_BAD
    LDAA P_BUFFER
    ASLA
    ASLA
    ASLA
    ASLA
    ORAA P_BUFFER + 1
    STAA P_HEADER
    ANDA #63
    CMPA #40
    BCC P_BAD
    LDAA #2
    STAA P_POS
    CLR P_PREFIX
    LDAA P_HEADER
    BITA #128
    BNE P_EXTENDED
    BITA #64
    BNE P_BAD
    BRA P_VALIDATE_COUNT
P_EXTENDED:
    LDAA P_LEN
    CMPA #5
    BCS P_BAD
    LDAA P_BUFFER + 2
    LDAB P_HEADER
    BITB #64
    BEQ P_PREFIX_VALUE
    ORAA #16
P_PREFIX_VALUE:
    TSTA
    BEQ P_BAD
    CMPA #21
    BCC P_BAD
    STAA P_PREFIX
    INC P_POS
P_VALIDATE_COUNT:
    LDAA P_LEN
    SUBA #2
    STAA P_LIMIT
    SUBA P_POS
    ADDA P_PREFIX
    CMPA #21
    BCC P_BAD
    ; All validation precedes writes to BEST or LEVEL.
    LDX #P_RECORD
    LDAB P_PREFIX
P_FILL_PREFIX:
    TSTB
    BEQ P_EXPAND_BODY
    LDAA #3
    STAA 0,X
    STAA 1,X
    INX
    INX
    DECB
    BRA P_FILL_PREFIX
P_EXPAND_BODY:
    STX DST
P_EXPAND_NEXT:
    LDAA P_POS
    CMPA P_LIMIT
    BEQ P_FILL_END
    LDX #P_BUFFER
    JSR N_INDEX
    LDAA 0,X
    STAA P_VALUE
    LSRA
    LSRA
    LDX DST
    STAA 0,X
    LDAA P_VALUE
    ANDA #3
    STAA 1,X
    INX
    INX
    STX DST
    INC P_POS
    BRA P_EXPAND_NEXT
P_FILL_END:
    LDX DST
    CLRA
P_FILL_ZERO:
    CPX #P_RECORD + 40
    BEQ P_COMMIT
    STAA 0,X
    INX
    BRA P_FILL_ZERO
P_COMMIT:
    LDX #P_RECORD
    STX SRC
    LDX #BEST
    STX DST
    LDX #40
    STX COUNT
    JSR COPY
    LDAA P_HEADER
    ANDA #63
    STAA LEVEL
    JMP C_SELECT
