MODE: .equ $3340
LEVEL: .equ $3341
ACTION: .equ $3342
N_LAST: .equ $3343
N_TMP: .equ $3344
N_ACC: .equ $3345
N_ARG0: .equ $3346
N_ARG1: .equ $3347
N_ARG2: .equ $3348
N_PCG: .equ $3349
N_PTR: .equ $334A
B_ARRAY: .equ $3600
C_ARRAY: .equ $3680
D_ARRAY: .equ $3700
GAME_START:
SHOW_TITLE:
    CLR MODE
    LDX #TITLE_PCG
    JSR LOAD_PCG
    LDX #MUSIC_TITLE
    JSR PLAY_MUSIC
    LDX #TITLE_SCREEN
    JSR N_SCREEN
    JMP FRAME_READY
IDLE:
    JSR CLOCK_SERVICE
    JSR INPUT_CAPTURE
    LDAA KEY_PENDING
    BNE DISPATCH
    LDAA MODE
    CMPA #1
    BNE IDLE
    LDAA TICK
    SUBA N_LAST
    CMPA #GAME_RATE
    BCS IDLE
    LDAA TICK
    STAA N_LAST
    JSR FN_TICK
    JMP N_DRAW
DISPATCH:
    STAA ACTION
    CLR KEY_PENDING
    LDAA MODE
    BEQ N_TITLE_INPUT
    CMPA #1
    BEQ N_GAME_INPUT
    CMPA #5
    BEQ SHOW_TITLE
    LDAB ACTION
    CMPB #5
    BNE FRAME_READY
    CMPA #2
    BEQ N_ADVANCE
    CMPA #3
    BEQ N_RETRY
    JMP SHOW_TITLE
N_TITLE_INPUT:
    LDAA ACTION
    CMPA #5
    BEQ N_START
    LDAA #5
    STAA MODE
    LDX #HELP_SCREEN
    JSR N_SCREEN
    JMP FRAME_READY
N_START:
    CLR LEVEL
N_NEW_LEVEL:
    LDX #$3400
    CLRA
N_CLEAR:
    STAA 0,X
    INX
    CPX #$3780
    BNE N_CLEAR
    LDAA #1
    STAA MODE
    JSR SOUND_STOP
    LDX #GAME_PCG
    JSR LOAD_PCG
    LDAA TICK
    STAA N_LAST
    LDAA LEVEL
    ASLA
    LDX #N_LEVEL_TABLE
    JSR N_INDEX
    LDX 0,X
    STX SRC
    LDX #D_ARRAY
    STX DST
    LDX #128
    STX COUNT
    JSR COPY
    JSR FN_INIT
    JMP N_DRAW
N_ADVANCE:
    INC LEVEL
    LDAA LEVEL
    CMPA #GAME_LEVELS
    BCS N_NEW_LEVEL
    DEC LEVEL
    LDAA #4
    STAA MODE
    JMP N_DRAW
N_GAME_INPUT:
    LDAA ACTION
    CMPA #6
    BEQ N_SPACE_RETRY
    JSR FN_ACT
    JMP N_DRAW
N_SPACE_RETRY:
    JMP N_RETRY
N_RETRY:
    JSR CONFIRM_RESET
    TSTA
    BNE N_NEW_LEVEL
N_DRAW:
    LDX #HUD_SCREEN
    STX SRC
    LDX #FRAMEBUFFER
    STX DST
    LDX #768
    STX COUNT
    JSR COPY
    JSR FN_DRAW
    LDAA LEVEL
    INCA
    LDX #FRAMEBUFFER + 29
    JSR NUMBER
    LDAA MODE
    CMPA #1
    BEQ N_PRESENT
    LDX #STATUS_CLEAR
    CMPA #2
    BEQ N_STATUS
    LDX #STATUS_LOSE
    CMPA #3
    BEQ N_STATUS
    LDX #STATUS_END
N_STATUS:
    STX TEXT_PTR
    LDX #FRAMEBUFFER + 21 * 32 + 1
    STX TEXT_OUT
    JSR TEXT
N_PRESENT:
    JSR PRESENT
FRAME_READY:
    JMP IDLE
N_SCREEN:
    STX SRC
    LDX #FRAMEBUFFER
    STX DST
    LDX #768
    STX COUNT
    JSR COPY
    JMP PRESENT
N_INDEX:
    TSTA
    BEQ N_INDEX_END
    INX
    DECA
    BRA N_INDEX
N_INDEX_END:
    RTS
N_MUL:
    STAA N_TMP
    CLRA
N_MUL_LOOP:
    TSTB
    BEQ N_MUL_END
    ADDA N_TMP
    DECB
    BRA N_MUL_LOOP
N_MUL_END:
    RTS
N_DIV:
    STAB N_TMP
    CLR N_ACC
    TSTB
    BEQ N_DIV_END
N_DIV_LOOP:
    CMPA N_TMP
    BCS N_DIV_END
    SUBA N_TMP
    INC N_ACC
    BRA N_DIV_LOOP
N_DIV_END:
    LDAB N_ACC
    STAA N_TMP
    TBA
    RTS
N_MOD:
    JSR N_DIV
    LDAA N_TMP
    RTS
N_SHL:
    TSTB
    BEQ N_SHIFT_END
    ASLA
    DECB
    BRA N_SHL
N_SHR:
    TSTB
    BEQ N_SHIFT_END
    LSRA
    DECB
    BRA N_SHR
N_SHIFT_END:
    RTS
N_XY:
    LDX #FRAMEBUFFER
    LDAB N_ARG1
N_XY_ROW:
    TSTB
    BEQ N_XY_COL
    ADX #32
    DECB
    BRA N_XY_ROW
N_XY_COL:
    LDAA N_ARG0
    JMP N_INDEX
N_TEXT:
    JSR N_XY
    STX TEXT_OUT
    JMP TEXT
N_NUMBER:
    JSR N_XY
    LDAA N_ARG2
    JMP NUMBER
N_LETTER:
    JSR N_XY
    LDAA N_ARG2
    SUBA #32
    STAA 0,X
    RTS
N_TILE:
    JSR N_XY
    LDAA N_ARG2
    ANDA #7
    ASLA
    ASLA
    ADDA #$80
    STAA 0,X
    INCA
    STAA 1,X
    INCA
    STAA 32,X
    INCA
    STAA 33,X
    RTS
N_SOUND:
    LDAA N_ARG0
    ANDA #3
    ASLA
    LDX #SFX_TABLE
    JSR N_INDEX
    LDX 0,X
    JMP PLAY_SFX
N_WIN:
    LDAA #2
    STAA MODE
    LDAA #2
    STAA N_ARG0
    JMP N_SOUND
N_LOSE:
    LDAA #3
    STAA MODE
    LDAA #3
    STAA N_ARG0
    JMP N_SOUND
