; SPDX-License-Identifier: MIT
; Turn dispatch, difficulty selection, and new adventure state.
NEW_GAME:
    CLR G_CLEAR_SUNG
    CLR G_WAND_SLOT
    LDAB G_SEED + 1
    LDAA G_SEED
    STAB G_RNG + 1
    STAA G_RNG
    LDX #G_X
    CLRA
NEW_ZERO:
    STAA 0,X
    INX
    CPX #G_RNG
    BNE NEW_ZERO
    LDX #G_BAG
NEW_BAG_ZERO:
    STAA 0,X
    INX
    CPX #G_SEED
    BNE NEW_BAG_ZERO
    CLR G_FLOOR
    CLR G_SUSPEND
    CLR G_MENU
    LDAB #((FRAME_READY) & 255)
    LDAA #((FRAME_READY) >> 8)
    STAB G_READY_ADDRESS + 1
    STAA G_READY_ADDRESS
    LDAB #(($5244) & 255)
    LDAA #(($5244) >> 8)
    STAB G_MAGIC + 1
    STAA G_MAGIC
    LDAB #(($3031) & 255)
    LDAA #(($3031) >> 8)
    STAB G_MAGIC + 2 + 1
    STAA G_MAGIC + 2
    LDAA #3
    STAA G_ATTACK
    LDAA #1
    STAA G_LEVEL
    CLR G_POISON
    CLR G_POISON_TICK
    CLR G_AUTOWALK
    LDX #DIFFICULTY_DEPTH
    LDAB G_DIFFICULTY
    STAB INDEX_OFFSET + 1
    ADX INDEX_OFFSET
    LDAA 0,X
    STAA G_DEPTH
    LDX #DIFFICULTY_HP
    LDAB G_DIFFICULTY
    STAB INDEX_OFFSET + 1
    ADX INDEX_OFFSET
    LDAA 0,X
    STAA G_HP
    STAA G_MAX_HP
    LDX #DIFFICULTY_FOOD
    STAB INDEX_OFFSET + 1
    ADX INDEX_OFFSET
    LDAA 0,X
    STAA G_FOOD
    LDAB #(($0001) & 255)
    LDAA #(($0001) >> 8)
    STAB G_IDENTITIES + 1
    STAA G_IDENTITIES
    LDAA #2
    STAA G_IDENTITIES + 2
    LDAB #(($0304) & 255)
    LDAA #(($0304) >> 8)
    STAB G_IDENTITIES + 3 + 1
    STAA G_IDENTITIES + 3
    JSR RANDOM
    ANDA #1
    BEQ SHUFFLE_SECOND
    LDAB #(($0100) & 255)
    LDAA #(($0100) >> 8)
    STAB G_IDENTITIES + 1
    STAA G_IDENTITIES
SHUFFLE_SECOND:
    JSR RANDOM
    ANDA #1
    BEQ SHUFFLE_SCROLL
    LDAA G_IDENTITIES + 1
    LDAB G_IDENTITIES + 2
    STAB G_IDENTITIES + 1
    STAA G_IDENTITIES + 2
SHUFFLE_SCROLL:
    JSR RANDOM
    ANDA #1
    BEQ SHUFFLE_DONE
    LDAB #(($0403) & 255)
    LDAA #(($0403) >> 8)
    STAB G_IDENTITIES + 3 + 1
    STAA G_IDENTITIES + 3
SHUFFLE_DONE:
    LDAA #5
    STAA G_IDENTITIES + 5
    LDAA #6
    STAA G_IDENTITIES + 6
    LDAA #7
    STAA G_IDENTITIES + 7
    JSR RANDOM
    ANDA #3
    TAB
    LDX #POTION_SLOTS
    STAB INDEX_OFFSET + 1
    ADX INDEX_OFFSET
    LDAB 0,X
    LDX #G_IDENTITIES
    STAB INDEX_OFFSET + 1
    ADX INDEX_OFFSET
    LDAA 0,X
    LDAB G_IDENTITIES + 5
    STAB 0,X
    STAA G_IDENTITIES + 5
    LDAA #6
    STAA COUNT
SHUFFLE_NEW_SCROLL:
    JSR RANDOM
    ANDA #3
    TAB
    LDX #SCROLL_SLOTS
    STAB INDEX_OFFSET + 1
    ADX INDEX_OFFSET
    LDAB 0,X
    LDX #G_IDENTITIES
    STAB INDEX_OFFSET + 1
    ADX INDEX_OFFSET
    LDAA 0,X
    PSHA
    STX P1
    LDAB COUNT
    LDX #G_IDENTITIES
    STAB INDEX_OFFSET + 1
    ADX INDEX_OFFSET
    LDAA 0,X
    PULB
    STAB 0,X
    LDX P1
    STAA 0,X
    INC COUNT
    LDAA COUNT
    CMPA #8
    BNE SHUFFLE_NEW_SCROLL
    JSR GENERATE_WORLD
    CLR G_FLOOR
    JSR SELECT_FLOOR
    LDAA #1
    STAA G_MODE
    CLR G_MESSAGE
    JSR UPDATE_VISIBILITY
    RTS
REDRAW:
    JSR RENDER_SCREEN
    JSR END_FEEDBACK
    JSR POLL_KEY
FRAME_READY:
    NOP
IDLE:
    JSR POLL_KEY
    TST G_MODE
    BNE IDLE_SEED_DONE
    LDAB G_SEED + 1
    LDAA G_SEED
    ADDB #((1) & 255)
    ADCA #((1) >> 8)
    JSR WORD_Z
    BNE SEED_NONZERO
    ADDB #((1) & 255)
    ADCA #((1) >> 8)
SEED_NONZERO:
    STAB G_SEED + 1
    STAA G_SEED
    JSR TITLE_SHIMMER
IDLE_SEED_DONE:
    LDAA G_PENDING
    BNE DISPATCH
    LDAA G_MODE
    CMPA #7
    BEQ FRAME_READY
    TST G_AUTOWALK
    BEQ IDLE
    LDAB G_REPEAT + 1
    LDAA G_REPEAT
    ADDB #((1) & 255)
    ADCA #((1) >> 8)
    STAB G_REPEAT + 1
    STAA G_REPEAT
    SUBB #((150) & 255)
    SBCA #((150) >> 8)
    BCS IDLE
    CLRA
    CLRB
    STAB G_REPEAT + 1
    STAA G_REPEAT
    JSR SAFE_WALK
    TST SAFE_FLAG
    BNE REPEAT_STEP
    CLR G_AUTOWALK
    BRA IDLE
REPEAT_STEP:
    LDAA G_PREVIOUS
    STAA G_KEY
    JSR WORLD_DIRECTION
    JMP REDRAW
DISPATCH:
    STAA G_KEY
    CLR G_PENDING
    CLR G_AUTOWALK
    CLRA
    CLRB
    STAB G_REPEAT + 1
    STAA G_REPEAT
    LDAA G_MODE
    BEQ TITLE_INPUT
    CMPA #1
    BEQ WORLD_INPUT
    CMPA #5
    BEQ INSPECT_INPUT
    CMPA #7
    BEQ SUSPEND_INPUT
    CMPA #8
    BCC END_INPUT
    JSR MENU_INPUT
    JMP REDRAW
TITLE_INPUT:
    LDAA G_KEY
    CMPA #5
    BEQ TITLE_START
    CMPA #1
    BEQ DIFFICULTY_UP
    CMPA #2
    BNE TITLE_DONE
DIFFICULTY_UP:
    LDAA G_DIFFICULTY
    LDAB #2
    JSR WRAP_CURSOR
    STAA G_DIFFICULTY
TITLE_DONE:
    JMP REDRAW
TITLE_START:
    JSR NEW_GAME
    JMP REDRAW
WORLD_INPUT:
    LDAA G_KEY
    CMPA #5
    BEQ OPEN_MENU
    CMPA #6
    BEQ WORLD_DONE
    CMPA #11
    BEQ WORLD_WAIT
    JSR WORLD_DIRECTION
WORLD_DONE:
    JMP REDRAW
WORLD_WAIT:
    CLR G_MESSAGE
    JSR COMMIT_TURN
    JMP REDRAW
OPEN_MENU:
    LDAA #2
    STAA G_MODE
    CLR G_MENU
    JMP REDRAW
INSPECT_INPUT:
    JSR INSPECT_MOVE
    JMP REDRAW
SUSPEND_INPUT:
    LDAA G_KEY
    CMPA #5
    BNE SUSPEND_STAY
    CLR G_SUSPEND
    LDAA #1
    STAA G_MODE
SUSPEND_STAY:
    JMP REDRAW
END_INPUT:
    LDAA G_KEY
    CMPA #5
    BNE END_STAY
    CLR G_MODE
END_STAY:
    JMP REDRAW
